duchy encryption
world-federation-of-advertisers/consent-signaling-client pull request #10
Opened 2021-07-28 01:59 UTC by stevenwarejones

2021-07-28 21:57 UTC, SanjayVas requested changes
> Reviewed 5 of 39 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: 5 of 60 files reviewed, 7 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj6IDX4Dl8KScK2mkh:-Mfj6IDX4Dl8KScK2mki:bj2dgsy) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L43)):*
> ```Kotlin
> val DUCHY_AGG_KEY_FILE = TESTDATA_DIR_PATH.resolve("aggregator.key").toFile()
> 
> val KEY_ALGORITHM = "EC"
> ```

You should only need the key algorithm constant for encryption key pairs. For certificate keys, you can determine the key algorithm from the public key in the corresponding certificate.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 50 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj3rMI0q6UtatIQsi2:-Mfj3rMI0q6UtatIQsi3:bkuceau) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L50)):*
> ```
> MC_X509
> ```
Don't reuse cert keys for encryption, even in tests. Also don't reuse certs/keys for different entities.

The risk is that someone may look at test code to figure out how things are supposed to be populated and get the wrong idea.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 83 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj1tH08bcTfHS7RXEW:-Mfj1tH08bcTfHS7RXEX:bsw70du) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L83)):*
> ```Kotlin
>  * [aggregatorCertificate] is required to determine the algorithm type of the signature
>  */
> suspend fun signAndEncryptResult(
> ```

I don't like how many parameters end up going into this function. That and the "and" in the name implies that this function perhaps has too much responsibility by doing more than one thing.

I think it'd be clearer to split into a separate `signResult` that returns a `SignedData` and an `encryptResult` that takes in that `SignedData`.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 84 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj38m002dMVmGkDAhD:-Mfj38m002dMVmGkDAhE:bpuc3x0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L84)):*
> ```Kotlin
>  */
> suspend fun signAndEncryptResult(
>   hybridCryptor: HybridCryptor,
> ```

Which HybridCryptor instance is used is derived from the cipher suite in the `EncryptionPublicKey`. Therefore, this shouldn't be a parameter. Probably want a util function that returns the appropriate instance for a given cipher suite.

This means that we'd want a cipher suite for the reversing crypto defined in the public API prior to this PR.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 86 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj4tTE1z1MJcnQNqdn:-Mfj4tTE1z1MJcnQNqdo:b3iyzaq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L86)):*
> ```Kotlin
>   hybridCryptor: HybridCryptor,
>   measurementResult: ByteString,
>   privateKeyHandle: PrivateKeyHandle,
> ```

Make it clear that this private key is the one that goes with the certificate.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 87 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj1d6BDQmH1KosVJZp:-Mfj1d6BDQmH1KosVJZq:b-djx5h2) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L87)):*
> ```
> ByteString
> ```
Prefer going to specific types as earlier as possible. The certificates here can already be read into X509Certificate objects.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 92 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj5DNF1UvzfJPtPlej:-Mfj5DNF1UvzfJPtPlek:bpcgp4z) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L92)):*
> ```Kotlin
> ): ByteString {
>   val privateKey: PrivateKey =
>     requireNotNull(privateKeyHandle.toJavaPrivateKey(readCertificate(duchyCertificate)))
> ```

Why are there two certs here? And why is one cert being used when converting to a Java private key and another to determine the algorithm for signing?

The result signature should be verifiable using the cert of the Duchy acting as the Aggregator.


<!-- Sent from Reviewable.io -->

2021-07-29 18:40 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: 2 of 63 files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 43 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj6IDX4Dl8KScK2mkh:-MfnMmhlA7yrQGzQUZKY:bfhvuko) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You should only need the key algorithm constant for encryption key pairs. For certificate keys, you can determine the key algorithm from the public key in the corresponding certificate.
</blockquote></details>

removed it. lmk if i did it correctly using `aggregatorX509.getPublicKey().algorithm`
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 50 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj3rMI0q6UtatIQsi2:-MfnN-TQ4A8ar6dJMrcY:b-iqp3uc) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> MC_X509
> ```
Don't reuse cert keys for encryption, even in tests. Also don't reuse certs/keys for different entities.

The risk is that someone may look at test code to figure out how things are supposed to be populated and get the wrong idea.
</blockquote></details>

okay - should we add a follow-up PR for generating key pairs in common-jvm?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 83 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj1tH08bcTfHS7RXEW:-MfnPYX859wMhXVhrvda:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't like how many parameters end up going into this function. That and the "and" in the name implies that this function perhaps has too much responsibility by doing more than one thing.

I think it'd be clearer to split into a separate `signResult` that returns a `SignedData` and an `encryptResult` that takes in that `SignedData`.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 84 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj38m002dMVmGkDAhD:-MfnMFeE8gr1fA1GZuyo:b-qdl45a) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Which HybridCryptor instance is used is derived from the cipher suite in the `EncryptionPublicKey`. Therefore, this shouldn't be a parameter. Probably want a util function that returns the appropriate instance for a given cipher suite.

This means that we'd want a cipher suite for the reversing crypto defined in the public API prior to this PR.
</blockquote></details>

I don't think it needs to be in public api. For now, I passed in a function to map ciphersuites and mocked it up for now. Does that work for you?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 86 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj4tTE1z1MJcnQNqdn:-MfnOScY7eprv8w-COyN:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make it clear that this private key is the one that goes with the certificate.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 87 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj1d6BDQmH1KosVJZp:-MfnNfD7BNbaqav59MK4:b-r02sp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ByteString
> ```
Prefer going to specific types as earlier as possible. The certificates here can already be read into X509Certificate objects.
</blockquote></details>

changed all these to pass type `X509Certificate` around. I know sometimes you like immutable Bytestrings being passed around. Can you help me understand better when to use ByteString?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 92 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj5DNF1UvzfJPtPlej:-MfnPV3-0trKFlI-RL2I:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why are there two certs here? And why is one cert being used when converting to a Java private key and another to determine the algorithm for signing?

The result signature should be verifiable using the cert of the Duchy acting as the Aggregator.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-30 00:32 UTC, SanjayVas requested changes
> Reviewed 7 of 8 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: 10 of 63 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/HybridEncryptionMapperForKemDem.kt, line 20 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-MfohzoQEe4wDP-gqrbq:-MfohzoQEe4wDP-gqrbr:b-7xilgy) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/HybridEncryptionMapperForKemDem.kt#L20)):*
> ```Kotlin
> 
> /** Maps based on kem and dem types. */
> class HybridEncryptionMapperForKemDem : HybridEncryptionMapper {
> ```

I don't think we need multiple HybridEncryptionMapper impls. It should just be one function that determines the mapping from the `HybridCipherSuite`.

We'd describe the cipher suite for reversing cryptor to have no KEM (since I believe it doesn't use the recipient public key at all) and a DEM of `REVERSE_BYTES`, documenting that these values must not be used in production.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 50 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj3rMI0q6UtatIQsi2:-MfoixCI5foj__QIHQU5:b6s8x8p) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L50)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

okay - should we add a follow-up PR for generating key pairs in common-jvm?
</blockquote></details>

Yeah. Obviously as you've determined here, we can just use arbitrary bytes for now as our fake cipher suite doesn't use it.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 84 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj38m002dMVmGkDAhD:-MfokarI8hXt8yPIBWcb:b1wn4fv) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L84)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think it needs to be in public api. For now, I passed in a function to map ciphersuites and mocked it up for now. Does that work for you?
</blockquote></details>

My reasoning for having it in the API is that it's an existing clear mechanism for specifying which ciphers are used, rather than needing to determine that from e.g. command-line flags/configuration. Instead, we can just have flags that indicate which cipher suites are allowed (which we might need anyway if we ever add a new cipher suite and deprecate and old one). Keep in mind that we'll likely be bringing the whole system up with the fake cryptor for the correctness test.

That said, if you additionally want to support swapping out the cryptor provider in tests, the mechanism we use for that is constructor dependency injection. These functions would become methods of a class, and we'd take in the provider function in the constructor defaulting to the real provider. See how `BlobKeyGenerator` is handled in [`RequisitionStore`](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2f55e521029c5838b5dc610de82bbd938fb029b/src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt) for an example. Basically since we only ever need one provider in production, you shouldn't ever see that there could possibly be more than one in the production path.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 87 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj1d6BDQmH1KosVJZp:-MfojTLa5-2L8AF-qlCy:b-dicrxy) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L87)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

changed all these to pass type `X509Certificate` around. I know sometimes you like immutable Bytestrings being passed around. Can you help me understand better when to use ByteString?
</blockquote></details>

Use ByteString for immutable bytes, e.g. when you might otherwise use ByteArray but have no need to mutate the bytes in-place. Separately, prefer known structured types when possible rather than their string or byte representations. e.g. don't serialize proto messages into bytes until you need to, and use X509Certificate for certs (which also happens to be immutable).
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 76 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfogwxk-q8eRSUinXQQ:-Mfogwxk-q8eRSUinXQR:b2i9go0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L76)):*
> ```
> serialized
> ```
nit: the `SignedData` isn't serialized here (it happens when `toByteString` is called on it in `encryptResult`). The measurement result, however, will be serialized here as the `data` of the returned `SignedData`.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 80 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-MfohdJ05JdUSAnCiVIH:-MfohdJ05JdUSAnCiVII:b-qnh2z) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L80)):*
> ```
> ByteString
> ```
Shouldn't this be a `Measurement.Result` message from the v2alpha public API?


<!-- Sent from Reviewable.io -->

2021-07-31 00:00 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: 10 of 63 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 83 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-MftpJtABQUNc_sDDn10:-MftpJtB8E-BksRDIjxp:bavilk0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L83)):*
> ```
>   aggregatorKeyHandle: PrivateKeyHandle,
>   aggregatorCertificate: X509Certificate,
> ): SignedData {
> ```

we also need to support duchy signing the elgamalPublicKey, which will be like

```
suspend fun signElgamalKey(
  elgamalKey: ByteString,
  /** This private key is paired with the [duchyCertificate] */
  duchyKeyHandle: PrivateKeyHandle,
 duchyCertificate: X509Certificate,
): SignedData {
  val privateKey: PrivateKey =
    requireNotNull(duchyKeyHandle.toJavaPrivateKey(duchyCertificate))
  val elgamalKeySignature =
    privateKey.sign(certificate = duchyCertificate, data = elgamalKey)
  val signedData =
    SignedData.newBuilder()
      .apply {
        data = elgamalKey
        signature = elgamalKeySignature
      }
      .build()
  return signedData
}

```
As you can see, the code is almost identical to this signResult() method.

so, it seems we need a generic helper method to sign any data using a privateKeyHandle and certificate. These client specific methods just call it.


<!-- Sent from Reviewable.io -->

2021-08-02 14:52 UTC, corbantek reviewed
> Reviewed 10 of 42 files at r2, 11 of 40 files at r5, 34 of 39 files at r6, 7 of 8 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-02 16:45 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/HybridEncryptionMapperForKemDem.kt, line 20 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-MfohzoQEe4wDP-gqrbq:-Mg6EiOtE_2NWl2yQvnp:bgg3743) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/HybridEncryptionMapperForKemDem.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we need multiple HybridEncryptionMapper impls. It should just be one function that determines the mapping from the `HybridCipherSuite`.

We'd describe the cipher suite for reversing cryptor to have no KEM (since I believe it doesn't use the recipient public key at all) and a DEM of `REVERSE_BYTES`, documenting that these values must not be used in production.
</blockquote></details>

changed this to a util function
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 84 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj38m002dMVmGkDAhD:-Mg6iqguEm_aYTgmDWbm:b-gvn4cf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My reasoning for having it in the API is that it's an existing clear mechanism for specifying which ciphers are used, rather than needing to determine that from e.g. command-line flags/configuration. Instead, we can just have flags that indicate which cipher suites are allowed (which we might need anyway if we ever add a new cipher suite and deprecate and old one). Keep in mind that we'll likely be bringing the whole system up with the fake cryptor for the correctness test.

That said, if you additionally want to support swapping out the cryptor provider in tests, the mechanism we use for that is constructor dependency injection. These functions would become methods of a class, and we'd take in the provider function in the constructor defaulting to the real provider. See how `BlobKeyGenerator` is handled in [`RequisitionStore`](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2f55e521029c5838b5dc610de82bbd938fb029b/src/main/kotlin/org/wfanet/measurement/duchy/storage/RequisitionStore.kt) for an example. Basically since we only ever need one provider in production, you shouldn't ever see that there could possibly be more than one in the production path.
</blockquote></details>

So, I don't think its good at this point to refactor these as classes. However, I did change the encrypt function to take an optional function as input to return the correct HybridCryptor. I think this should work until we have actual real tink hybrid encryption support.

I'm also still not a fan of introducing test encryption into the public API. I'd prefer more how it is now. Does this work for the time being?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 87 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj1d6BDQmH1KosVJZp:-Mg617rcCSAHei5lz3nJ:b-m96034) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use ByteString for immutable bytes, e.g. when you might otherwise use ByteArray but have no need to mutate the bytes in-place. Separately, prefer known structured types when possible rather than their string or byte representations. e.g. don't serialize proto messages into bytes until you need to, and use X509Certificate for certs (which also happens to be immutable).
</blockquote></details>

thanks for the clarification. very helpful
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 76 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfogwxk-q8eRSUinXQQ:-Mg5zqMV4fYNF98g9ajM:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> serialized
> ```
nit: the `SignedData` isn't serialized here (it happens when `toByteString` is called on it in `encryptResult`). The measurement result, however, will be serialized here as the `data` of the returned `SignedData`.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 80 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-MfohdJ05JdUSAnCiVIH:-Mg610VGBTlNXV3XhaA0:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ByteString
> ```
Shouldn't this be a `Measurement.Result` message from the v2alpha public API?
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 83 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-MftpJtABQUNc_sDDn10:-Mg68avS1ZtbqIVTiq0v:bs4krcp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1d62149e8a4062b74013de7b4ca850adf2ffe92d/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L83)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>   aggregatorKeyHandle: PrivateKeyHandle,
>   aggregatorCertificate: X509Certificate,
> ): SignedData {
> ```

we also need to support duchy signing the elgamalPublicKey, which will be like

```
suspend fun signElgamalKey(
  elgamalKey: ByteString,
  /** This private key is paired with the [duchyCertificate] */
  duchyKeyHandle: PrivateKeyHandle,
 duchyCertificate: X509Certificate,
): SignedData {
  val privateKey: PrivateKey =
    requireNotNull(duchyKeyHandle.toJavaPrivateKey(duchyCertificate))
  val elgamalKeySignature =
    privateKey.sign(certificate = duchyCertificate, data = elgamalKey)
  val signedData =
    SignedData.newBuilder()
      .apply {
        data = elgamalKey
        signature = elgamalKeySignature
      }
      .build()
  return signedData
}

```
As you can see, the code is almost identical to this signResult() method.

so, it seems we need a generic helper method to sign any data using a privateKeyHandle and certificate. These client specific methods just call it.

</blockquote></details>

I templated this out. Lmk if you think that works. I still think the actual signElGamalKey function should be in this repo.


<!-- Sent from Reviewable.io -->

2021-08-02 17:47 UTC, corbantek approved these changes
> Reviewed 16 of 16 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-08-02 23:11 UTC, SanjayVas approved these changes
> Reviewed 15 of 16 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel, line 28 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg83A2x48wW4CEVouDF:-Mg83A2yAVSeY7clLyTz:b-yx0fjd) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel#L28)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption",
>         "//src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore",
>         "//src/main/proto/wfa/measurement/api/v2alpha:crypto_java_proto",
> ```

I thought I had left a comment on a previous PR regarding having the `crypto` package not depend on the API, and instead keeping all API dependencies in the `client` package.

The idea is that the `crypto` package is effectively just wrapping the underlying primitives with our interfaces.

Feel free to leave this as a TODO, as we'd also need to move the SignedData overload from Signatures that I missed in the previous PR.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 169 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg87L-61JR0TcGsHyAA:-Mg87L-61JR0TcGsHyAB:b-bjpfw5) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L169)):*
> ```
> ::fakeGetHybridCryptorForCipherSuite
> ```
nit: we don't really need this function defined, as we can simply pass a lambda that returns the `reversingHybridCryptor` instance.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 84 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mfj38m002dMVmGkDAhD:-Mg84ydLAYyw5p8ekKsQ:b-z5mypo) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4067a0639739e77053f3eaccfe24e701449b9904/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L84)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

So, I don't think its good at this point to refactor these as classes. However, I did change the encrypt function to take an optional function as input to return the correct HybridCryptor. I think this should work until we have actual real tink hybrid encryption support.

I'm also still not a fan of introducing test encryption into the public API. I'd prefer more how it is now. Does this work for the time being?
</blockquote></details>

Okay for the time being to unblock this PR. We may need to revisit depending on the shape of the correctness test and how we want to plumb the fake cryptor provider dependency from each`Server` class. e.g. whether we're okay with the fact that this likely means having fake encryption versions of each server defined as `testonly`.

Tagging @wangyaopw to keep an eye on that.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/testing/BUILD.bazel, line 6 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg84TAt6ajD3_aRosoj:-Mg84TAu3DGpDqxvjSug:b-r6sw0d) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/testing/BUILD.bazel#L6)):*
> ```Starlark
>     default_testonly = True,
>     default_visibility = [
>         "//src/main/kotlin/org/wfanet/measurement/consent/crypto/testing:__subpackages__",
> ```

I *think* that you can just use `:__subpackages__` instead of fully qualifying the current package name.


<!-- Sent from Reviewable.io -->

2021-08-03 00:25 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel, line 28 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg83A2x48wW4CEVouDF:-Mg8MnrP-LK5K4gB4A38:b7kyaaf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought I had left a comment on a previous PR regarding having the `crypto` package not depend on the API, and instead keeping all API dependencies in the `client` package.

The idea is that the `crypto` package is effectively just wrapping the underlying primitives with our interfaces.

Feel free to leave this as a TODO, as we'd also need to move the SignedData overload from Signatures that I missed in the previous PR.
</blockquote></details>

that is pulling from the public api. I thought that was fine.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 169 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg87L-61JR0TcGsHyAA:-Mg8NBTl1bIW70rydpmj:bsa0tue) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L169)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ::fakeGetHybridCryptorForCipherSuite
> ```
nit: we don't really need this function defined, as we can simply pass a lambda that returns the `reversingHybridCryptor` instance.
</blockquote></details>

i agree but I thought it might get reused a few times so added it for future convenience.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/testing/BUILD.bazel, line 6 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg84TAt6ajD3_aRosoj:-Mg8N9NzDvrSMUwMZlkT:bmmfwjf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/testing/BUILD.bazel#L6)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I *think* that you can just use `:__subpackages__` instead of fully qualifying the current package name.
</blockquote></details>

its exposed to `crypto/testing` vs `crypto/hybridencryptipn/testing` but thanks for the tip.


<!-- Sent from Reviewable.io -->

2021-08-03 00:44 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel, line 28 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg83A2x48wW4CEVouDF:-Mg8RWMTDBRVpfQP1FUc:b-8pdnfj) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

that is pulling from the public api. I thought that was fine.
</blockquote></details>

The `client` package can pull from the public API, but the `crypto` package shouldn't. That's the key factor separating the two packages.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 169 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10#-Mg87L-61JR0TcGsHyAA:-Mg8RqJS7x-Vce0QUXka:b-fcx50j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/c925b4351ad38276fd5600da11f87a45a0d29406/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L169)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i agree but I thought it might get reused a few times so added it for future convenience.
</blockquote></details>

Yes, but `fakeGetHybridCryptorForCipherSuite` returns a new instance whereas using a lambda would allow you to reuse the same instance defined in the test method.

While not an issue here, it could be useful if e.g. the alternate cryptor you want to inject has state.


<!-- Sent from Reviewable.io -->

2021-08-03 16:32 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/10)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-03 16:34 UTC, merged