Add remaining measurement consumer client functions
world-federation-of-advertisers/consent-signaling-client pull request #12
Opened 2021-08-06 04:43 UTC by corbantek

- Add the remaining client functions for measurement consumer
  - Sign RequisitionSpec
  - Encrypt RequisitionSpec
  - Sign MeasurementSpec
  - Verify Result
- Add corresponding unit tests (WIP)

2021-08-06 13:49 UTC, stevenwarejones requested changes
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @corbantek)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQhRmg1vp4zqC40Zzx:-MgQhRmg1vp4zqC40Zzy:buustow) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L39)):*
> ```Kotlin
>   requisitionSpec: RequisitionSpec,
>   measurementConsumerPrivateKeyHandle: PrivateKeyHandle,
>   measurementConsumerX509: ByteString
> ```

pass this in directly as type `X509Certificate`
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQhoX4AIpK8_44ikKA:-MgQhoX4AIpK8_44ikKB:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L69)):*
> ```Kotlin
>   measurementSpec: MeasurementSpec,
>   measurementConsumerPrivateKeyHandle: PrivateKeyHandle,
>   measurementConsumerX509: ByteString
> ```

ditto
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgQi-zj29Rs6qXptMm7:b-2inmow) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
> ```Kotlin
>   encryptionPublicKey: EncryptionPublicKey,
>   privateKeyHandle: PrivateKeyHandle,
>   measurementConsumerX509: ByteString
> ```

fix this too while you're at it


<!-- Sent from Reviewable.io -->

2021-08-06 14:26 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @corbantek and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgQq7oW0nq70z1AnK-c:b-8gnf7m) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

fix this too while you're at it
</blockquote></details>

This came from @wangyaopw and I'm wondering if we should keep it abstracted in ByteString form.  What if down the road we don't want to use java.security.cert.X509Certificate but something else that does X509?  We'd have to update every client call--where passing in the ByteString allows us to change implementation under the covers?

Its just a thought, either way I need to sync up with Yao if I change this function since I thin he's already using it.


<!-- Sent from Reviewable.io -->

2021-08-06 15:29 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @corbantek and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgR40PTA9LiZMBQyiT7:bc882yi) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

This came from @wangyaopw and I'm wondering if we should keep it abstracted in ByteString form.  What if down the road we don't want to use java.security.cert.X509Certificate but something else that does X509?  We'd have to update every client call--where passing in the ByteString allows us to change implementation under the covers?

Its just a thought, either way I need to sync up with Yao if I change this function since I thin he's already using it.
</blockquote></details>

If we want to overload it in the future, thats an even better reason to pass in X509Certificate type now. You can update this and it won't break Yao's stuff since he is pinned to a different commit.


<!-- Sent from Reviewable.io -->

2021-08-06 15:35 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @corbantek and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgR5Mn73Pin5BZAvpkL:-MgR5Mn73Pin5BZAvpkM:b7xfhc6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L40)):*
> ```Kotlin
>       RequisitionSpec.newBuilder()
>         .apply {
>           measurementPublicKey = EncryptionPublicKey.newBuilder().apply { publicKeyInfo = ByteString.copyFromUtf8("testPublicKey") }.build().toByteString()
> ```

you don't really need to build a serialized EncryptionPublicKey --- you could simplify with
`measurementPublicKey = ByteString.copyFromUtf8("some EncryptionPublicKey")
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgR4RqV1Xk_f5lm6tCY:-MgR4RqW5KUvcoCuHrJW:b-bslbyt) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L50)):*
> ```Kotlin
>       keyStore.storePrivateKeyDer(
>         mcPrivateKeyHandleKey,
>         ByteString.copyFrom(mcPrivateKey.encoded)
> ```

how is this different than `.getEncoded()`? I thought getEncoded was preferred.


<!-- Sent from Reviewable.io -->

2021-08-06 15:56 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @corbantek, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgR9Xss4UWIGiwfvi5W:b-w525wx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

If we want to overload it in the future, thats an even better reason to pass in X509Certificate type now. You can update this and it won't break Yao's stuff since he is pinned to a different commit.
</blockquote></details>

I'm not following here.  How does using the concrete class of java.security.cert.X509Certificate an even better reason?  If we wanted to change this function in the future to not use X509 from java, we'd have to update every client/caller with our new parameter type.

I'm just saying if we use ByteString we can update readCertificate inside our own method to some other class and the caller would never know we changed implementations away from X509.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgR5Mn73Pin5BZAvpkL:-MgR9GQU8a0MRzMpPw53:b-5w21k4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you don't really need to build a serialized EncryptionPublicKey --- you could simplify with
`measurementPublicKey = ByteString.copyFromUtf8("some EncryptionPublicKey")
</blockquote></details>

Yeah I know its a little extra, but doesn't hurt the test
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgR4RqV1Xk_f5lm6tCY:-MgR9Ml-4Vwy061GxWAj:b2bnxlq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L50)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how is this different than `.getEncoded()`? I thought getEncoded was preferred.
</blockquote></details>

My IDE kept complaining I wasn't doing it the "Kotlin" way and wanted me to not use "get*()" methods


<!-- Sent from Reviewable.io -->

2021-08-06 16:49 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgRLgIl79lInsOusR80:bgm05f0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

I'm not following here.  How does using the concrete class of java.security.cert.X509Certificate an even better reason?  If we wanted to change this function in the future to not use X509 from java, we'd have to update every client/caller with our new parameter type.

I'm just saying if we use ByteString we can update readCertificate inside our own method to some other class and the caller would never know we changed implementations away from X509.
</blockquote></details>

I would prefer using ByteString, since that is what is persisted in the kingdom DB and the data format the clients have. It is good that the caller doesn't need to know how to read it and let the client library deal with that.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgRMKYyBk2pzQd3ued-:-MgRMKYyBk2pzQd3ued0:b-9yu85g) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1b8a3dd62fea2f69d8120428016f049c7a3927af/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L79)):*
> ```Kotlin
> 
> /** Signs the measurementConsumer's encryptionPublicKey. */
> suspend fun signEncryptionPublicKey(
> ```

mcClient also needs method verifyEncrptionPublicKey(), which is used to verify the EDP's public keys.


<!-- Sent from Reviewable.io -->

2021-08-06 17:05 UTC, stevenwarejones reviewed
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgRPtaA7lYh_SIaSOkR:b-58bthc) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I would prefer using ByteString, since that is what is persisted in the kingdom DB and the data format the clients have. It is good that the caller doesn't need to know how to read it and let the client library deal with that.
</blockquote></details>

I was thinking if we want to overload this function in the future with different certificate types, then it is good to pass in a non-generic ByteString.

@sanjayvas - any thoughts?


<!-- Sent from Reviewable.io -->

2021-08-06 18:24 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgRMKYyBk2pzQd3ued-:-MgRhMCU5f25shtuiytq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/1b8a3dd62fea2f69d8120428016f049c7a3927af/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L79)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

mcClient also needs method verifyEncrptionPublicKey(), which is used to verify the EDP's public keys.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 18:46 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgRm1PQ0O_3ZFcAZDpS:b-3bb90j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was thinking if we want to overload this function in the future with different certificate types, then it is good to pass in a non-generic ByteString.

@sanjayvas - any thoughts?
</blockquote></details>

In the two verifyXXX() methods, it is using  `X509Certificate`. So I think we need to make them consistent. Either use  `X509Certificate` or use `ByteString` everywhere.


<!-- Sent from Reviewable.io -->

2021-08-06 18:47 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgRmX2uEAlF2Cnsa8hT:b5a0xko) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

In the two verifyXXX() methods, it is using  `X509Certificate`. So I think we need to make them consistent. Either use  `X509Certificate` or use `ByteString` everywhere.
</blockquote></details>

@wangyaopw I agree, but was waiting on the consensus, I was waiting for Oliver or @sanjayvas to express their opinion, then I'll make everything consistent


<!-- Sent from Reviewable.io -->

2021-08-06 21:34 UTC, SanjayVas reviewed
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @corbantek, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgSM8LH1cvupUkgo-G2:b-98oxm4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

@wangyaopw I agree, but was waiting on the consensus, I was waiting for Oliver or @sanjayvas to express their opinion, then I'll make everything consistent
</blockquote></details>

The general best practice is to use specific types when possible for function params. In this case, X509Certificate is a more specific type that represents an X.509 certificate in Java. Given that we also need to convert to that type to do anything useful with it in this method, it's pretty compelling to just specify that type in the method signature.

There are arguments about encapsulation if you want to treat a type as an implementation detail, but I don't really foresee us switching to something else. Even the most popular libraries (e.g. BouncyCastle) continue to use this part of the Java security API and just include utils and swap out the underlying providers. Even if we did change to something else, it would also mean we're making significant changes to handle certificates. Therefore, it's not worth treating the use of X509Certificate as an implementation detail.


<!-- Sent from Reviewable.io -->

2021-08-06 21:40 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @corbantek, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MgSOOuW9ayewFSIZJud:bc5d3n8) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The general best practice is to use specific types when possible for function params. In this case, X509Certificate is a more specific type that represents an X.509 certificate in Java. Given that we also need to convert to that type to do anything useful with it in this method, it's pretty compelling to just specify that type in the method signature.

There are arguments about encapsulation if you want to treat a type as an implementation detail, but I don't really foresee us switching to something else. Even the most popular libraries (e.g. BouncyCastle) continue to use this part of the Java security API and just include utils and swap out the underlying providers. Even if we did change to something else, it would also mean we're making significant changes to handle certificates. Therefore, it's not worth treating the use of X509Certificate as an implementation detail.
</blockquote></details>

I am good with either way. @corbantek your choice


<!-- Sent from Reviewable.io -->

2021-08-09 20:22 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @corbantek, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-MggZZR7200bh454jElc:b-g9wg6l) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I am good with either way. @corbantek your choice
</blockquote></details>

@wangyaopw After much though I'm going to change to X509Certificate (to be constant everywhere) and you can use exported function readCertificate().  I think down the road it would be nice to explore the layer that would call these methods but simplifies their usage for the MC and EDPs (like using the proto's directly)...


<!-- Sent from Reviewable.io -->

2021-08-09 20:55 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 2 of 6 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQhRmg1vp4zqC40Zzx:-MgggjlXDssSJsb654rR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

pass this in directly as type `X509Certificate`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQhoX4AIpK8_44ikKA:-MgggjIa4js5MRI1b3Pr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L69)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgQi-zj29Rs6qXptMm6:-Mgggj3s1rXvToK09VA_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/df67055c56e5df5ae074cc6fc6a0e9aad081dd4e/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L82)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

@wangyaopw After much though I'm going to change to X509Certificate (to be constant everywhere) and you can use exported function readCertificate().  I think down the road it would be nice to explore the layer that would call these methods but simplifies their usage for the MC and EDPs (like using the proto's directly)...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 20:56 UTC, wangyaopw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 4 files at r1, 2 of 2 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-:-MgggMEF267eGDhk3Ivy:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-08-09 21:22 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 96 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-Mggme6sACS50zYKLzyd:-Mggme6sACS50zYKLzye:b-qiylz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7570f1f719cd40f089097e7bfd904cd022c5f594/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L96)):*
> ```Kotlin
>  * 3. TODO: Verify certificate chain for [aggregatorCertificate]
>  */
> suspend fun verifyResult(
> ```

FYI, there should also be a DecryptResult() method.


<!-- Sent from Reviewable.io -->

2021-08-09 22:03 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 96 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-Mggme6sACS50zYKLzyd:-MggwBuT2ILqvwaclwD-:b3zkv10) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7570f1f719cd40f089097e7bfd904cd022c5f594/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L96)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

FYI, there should also be a DecryptResult() method.
</blockquote></details>

Not sure how I missed that, Thanks!

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 22:33 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 3 of 6 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @stevenwarejones, and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-08-09 23:56 UTC, SanjayVas requested changes
> Reviewed 2 of 4 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: all files reviewed, 13 unresolved discussions (waiting on @corbantek, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 38 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghGTM6Do6XmI1_zpOJ:-MghGTM70lAzheJaqu1o:b5y1pwj) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L38)):*
> ```
> measurementConsumerX509
> ```
nit: `measurementConsumerCertificate` reader better IMO, as well as matching the field name in the API and the naming  used by the other functions added by this PR
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 20 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghKdnpAfTfMBP6P2w5:-MghKdnpAfTfMBP6P2w6:bn0hhan) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L20)):*
> ```Kotlin
> import com.google.protobuf.ByteString
> import java.security.cert.X509Certificate
> import kotlin.test.assertEquals
> ```

Use Truth library for all equality checks, not `assertEquals`.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 82 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghGxJQ6sxtlF3E2mpM:-MghGxJQ6sxtlF3E2mpN:b-le0ysa) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L82)):*
> ```Kotlin
> 
> class MeasurementConsumerClientTest {
>   companion object {
> ```

nit: companion objects typically go at the end of the class
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 85 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghHMGj2XcBG9-Xii7e:-MghHMGj2XcBG9-Xii7f:b249nwu) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L85)):*
> ```
> setup
> ```
nit: prefer a more descriptive name
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 106 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghI4v98lHXVvksQhoe:-MghI4v98lHXVvksQhof:b-ky46md) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L106)):*
> ```Kotlin
> 
>   @Test
>   fun `measurementConsumer sign requisitionSpec`() = runBlocking {
> ```

nit: typical test naming would be something like "signRequisitionSpec returns valid signature", optionally indicating the condition if it's relevant (e.g. "foo throws exception when bar is invalid")
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 107 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghJ5nP5_CCOteQG3Y9:-MghJ5nQEENEaUEisLMA:bmzgxw3) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L107)):*
> ```
> aRequisitionSpec
> ```
nit: odd naming choice. Why not just `requisitionSpec`? There's no need to name this to read "a requisition spec".
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 144 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghJXUc2RoFqZTVLEfw:-MghJXUc2RoFqZTVLEfx:b-qyjnne) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L144)):*
> ```
> requireNotNull
> ```
`checkNotNull`, since this is checking application state rather than an argument
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 147 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghJkhp3uIlB5o8aeTr:-MghJkhp3uIlB5o8aeTs:bkgbjon) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L147)):*
> ```
> Truth.assertThat
> ```
Add an import so that we can reference `assertThat` directly.

We normally don't use class method imports, but there's an exception for assertions in tests for readability.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 183 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghHe-pE_pRP20NHGd2:-MghHe-pE_pRP20NHGd3:bilo1im) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L183)):*
> ```Kotlin
>   fun `measurementConsumer decrypt result`() = runBlocking {
>     val hybridCipherSuite = HybridCipherSuite.getDefaultInstance()
>     /** Encrypt a Result (as SignedData) using the Duchy Aggregator Functions */
> ```

nit: use regular comment syntax rather than KDoc syntax within a function
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 207 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghKGjr7qN1iTJIbOwu:-MghKGjr7qN1iTJIbOwv:b-mgni17) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L207)):*
> ```Kotlin
>     val decryptedResult = Measurement.Result.parseFrom(decryptedSignedDataResult.data)
> 
>     assertEquals(signedResult.toByteString(), decryptedSignedDataResult.toByteString())
> ```

Use ProtoTruth for assertions on protocol buffer messages.

e.g. `assertThat(decryptedSignedResult).isEqualTo(signedResult)` after importing `ProtoTruth.assertThat`


<!-- Sent from Reviewable.io -->

2021-08-10 15:01 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 1 of 6 files reviewed, 10 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt, line 38 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghGTM6Do6XmI1_zpOJ:-MgkQKHq8UVDOsGuM8yt:b-a0uqav) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/main/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClient.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> measurementConsumerX509
> ```
nit: `measurementConsumerCertificate` reader better IMO, as well as matching the field name in the API and the naming  used by the other functions added by this PR
</blockquote></details>

Done, fixed in all client files.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 20 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghKdnpAfTfMBP6P2w5:-MgkWg216thJDoeTxqz_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Truth library for all equality checks, not `assertEquals`.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 82 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghGxJQ6sxtlF3E2mpM:-MgkR5NL3dEUf_jhgzG0:bhr76l6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: companion objects typically go at the end of the class
</blockquote></details>

I think normally that would make senes, but this is being used as the weird Kotlin workaround for JUnit for running a test class init method.  I think it's more readable to have at the top since its initializing state for the tests below.  
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 85 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghHMGj2XcBG9-Xii7e:-MgkRrZ03vLOitrttx_D:b-sdmlcj) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> setup
> ```
nit: prefer a more descriptive name
</blockquote></details>

Done, changed to initializePrivateKeyKeystore()
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 106 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghI4v98lHXVvksQhoe:-MgkSbMB5ONG7SDo56lb:b-qrqosf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: typical test naming would be something like "signRequisitionSpec returns valid signature", optionally indicating the condition if it's relevant (e.g. "foo throws exception when bar is invalid")
</blockquote></details>

Fixed in entire file
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 107 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghJ5nP5_CCOteQG3Y9:-MgkSd7S-lvXQ2X4IqCf:b6szlz8) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> aRequisitionSpec
> ```
nit: odd naming choice. Why not just `requisitionSpec`? There's no need to name this to read "a requisition spec".
</blockquote></details>

Renamed all similar variables
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 144 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghJXUc2RoFqZTVLEfw:-MgkU1F03qqPsaUrjNTz:bn43sc6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L144)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> requireNotNull
> ```
`checkNotNull`, since this is checking application state rather than an argument
</blockquote></details>

Thanks, I wasn't aware checkNotNull existed.  I think I've only seen requireNotNull being used in a similar way in CMM repo, so probably should run a search.

I've updated entire file
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 147 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghJkhp3uIlB5o8aeTr:-MgkUgwMADirJHCuMXxo:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Truth.assertThat
> ```
Add an import so that we can reference `assertThat` directly.

We normally don't use class method imports, but there's an exception for assertions in tests for readability.
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 183 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghHe-pE_pRP20NHGd2:-MgkVuyb1ZeOHrm7ToWU:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/53a7b48838bf00e356582df0aac188a699998487/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L183)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use regular comment syntax rather than KDoc syntax within a function
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 207 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MghKGjr7qN1iTJIbOwu:-MgkWagf5YW3Kp5yNpgB:bb6un1j) ([raw file](https://github.com/world-f [...]

2021-08-10 15:21 UTC, stevenwarejones approved these changes
> Reviewed 4 of 5 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: all files reviewed, 7 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-08-10 16:53 UTC, SanjayVas approved these changes
> Reviewed 4 of 5 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: all files reviewed, 2 unresolved discussions (waiting on @corbantek, @oliver-amzn, and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 18 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgkygbM7cnIpuFPV7ly:-MgkygbM7cnIpuFPV7lz:b-6gipq1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ec4464091a4d27eb5974b5a7e3f3dd8e0b19b5a4/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L18)):*
> ```
> protoAssertThat
> ```
nit: you can just also call this `assertThat`. It doesn't create a naming conflict, and this way you don't have to worry about whether the subject is a protobuf message.


<!-- Sent from Reviewable.io -->

2021-08-10 17:41 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt, line 18 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12#-MgkygbM7cnIpuFPV7ly:-Mgl8xr7CqydAlkZSJZF:b-886gsx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ec4464091a4d27eb5974b5a7e3f3dd8e0b19b5a4/src/test/kotlin/org/wfanet/measurement/consent/client/measurementconsumer/MeasurementConsumerClientTest.kt#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> protoAssertThat
> ```
nit: you can just also call this `assertThat`. It doesn't create a naming conflict, and this way you don't have to worry about whether the subject is a protobuf message.
</blockquote></details>

Fixed


<!-- Sent from Reviewable.io -->

2021-08-10 18:14 UTC, wangyaopw approved these changes
> Reviewed 4 of 5 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek)



<!-- Sent from Reviewable.io -->

2021-08-10 18:16 UTC, merged