Add support for signing and validating Flows
world-federation-of-advertisers/consent-signaling-client pull request #16
Opened 2021-08-27 16:47 UTC by jonmolle

Used in panel exchange storage to sign and validate blob data. The storage
  extensions added in client allow for public access to the new signature
  functions.

- The signature returns a pair and requires the flow to be completed for the
  signature to be generated

- The validate step throws a custom DataFailsSignatureValidation if the Flow is
  invalid.

- Adds public helper extension functions in storage/Storage.kt that support
  signature matching (Blob.verifiedRead and StorageClient.createSignedBlob).

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)

2021-08-30 23:56 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi7gqJMCs7YWihNY2Hr:-MiOTQMD87G53kqTJzkl:b-j14zcp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4e6d9fa7214c2d6473544afe2b78a694957236fc/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe we add `src/main/kotlin/org/wfanet/measurement/consent/client/storage/StorageClient.kt` that defines:

```
fun StorageClient.getSignedBlob(blobKey: String, signatureBlobKey: String, certificate: X509Certificate): Blob?

fun StorageClient.createSignedBlob(blobKey: String, contents: Flow<ByteString>, signatureBlobKey: String, privateKey: PrivateKeyProviderOrWhateverItIsCalled)
```
</blockquote></details>

What I would prefer is to add functions here for model provider and data provider to import -- https://github.com/world-federation-of-advertisers/consent-signaling-client/tree/main/src/main/kotlin/org/wfanet/measurement/consent/client 

You would need to implement separate functions for data providers and model providers but they could both use the same template. You would then make those functions visible public.

That follows the convention of this repo for other clients. lmk if that makes sense.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi8IcB85dv07sDZT9IH:-MiOTC0q8BPme5XUkOv7:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f76a9e3c0e82269a8d2b721fbd6c230da4bb344e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just `InvalidSignatureException`? This name sounds a little weird to me.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2021-08-31 21:14 UTC, efoxepstein requested changes
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 5 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiT2daG-JarPE5pzUx0:-MiT2daH8Tekd67bktd4:b-z7fsow) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a32ef350ac4fee0d652190149145f20811c0f2ab/src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt#L57)):*
> ```Kotlin
> ): Pair<Blob, ByteString> {
>   val (contentFlow, deferredSig) = privateKey.signFlow(cert, content)
>   return this.createBlob(blobKey = blobKey, content = contentFlow) to deferredSig.await()
> ```

Out of curiosity does Kotlin guarantee a left to right evaluation order of arguments? It might be safer to pull blob creation out to a local variable before awaiting.


<!-- Sent from Reviewable.io -->

2021-08-31 22:35 UTC, jonmolle reviewed
I've added helper functions in client that allow indirect use outside of this repo

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-:-MiT72uM-26jRTcAYXHC:b-ve5g3g)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt, line 57 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiT2daG-JarPE5pzUx0:-MiT7BTo2KrU7qX2J10L:b10zkbe) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a32ef350ac4fee0d652190149145f20811c0f2ab/src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity does Kotlin guarantee a left to right evaluation order of arguments? It might be safer to pull blob creation out to a local variable before awaiting.
</blockquote></details>

Oh, I don't know. I followed the debugger through a few times working on the structure, but I'm not sure if that's a guarantee. Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi7gqJMCs7YWihNY2Hr:-MiT8mCz0jQzpPYAjfTc:b-4kr720) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4e6d9fa7214c2d6473544afe2b78a694957236fc/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

What I would prefer is to add functions here for model provider and data provider to import -- https://github.com/world-federation-of-advertisers/consent-signaling-client/tree/main/src/main/kotlin/org/wfanet/measurement/consent/client 

You would need to implement separate functions for data providers and model providers but they could both use the same template. You would then make those functions visible public.

That follows the convention of this repo for other clients. lmk if that makes sense.
</blockquote></details>

I've added helper extensions StorageClient.createSignedBlob and StorageClient.Blob.verifiedRead that invoke these. I have a PR in panel-exchange to make a wrapper that basically forces all I/O to use them (or will, the actual r/w functions are stubs right now).

I don't really understant the reason for different functions for model and data providers. If everyone is using StorageClient as the abstract interface they can implement whichever (even custom) client without these even needing to be aware what's going on. The panel-exchange wrapper will have to be a bit more clever (only in where to read and write the signatures from), but I can't see how any specific underlying client would affect that (although if I'm missing something here, or in that PR, I'm happy to update it).  
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi8IcB85dv07sDZT9IH:-MiT7K039q0SjacK55ZM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f76a9e3c0e82269a8d2b721fbd6c230da4bb344e/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi8JOocEXOAsqPsl2PD:-MiT8DVW2-IkJlJhCk0M:b-qzbl52) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1db03bbe1cbb806d9c58e1f179cde80b318bb83/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can we define `sign` in terms of `signFlow` to reduce duplication? Ditto for verify?
</blockquote></details>

It seems a little heavy for avoiding duplication, but done.
___
*[src/test/kotlin/org/wfanet/measurement/consent/crypto/SignaturesTest.kt, line 146 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi7e4RF4sdc_YRrOLDa:-MiTBPl_20cUUQzSQRxQ:b-40pynx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4e6d9fa7214c2d6473544afe2b78a694957236fc/src/test/kotlin/org/wfanet/measurement/consent/crypto/SignaturesTest.kt#L146)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Consistency
</blockquote></details>

Gotcha, Done.
___
*[src/test/kotlin/org/wfanet/measurement/consent/crypto/SignaturesTest.kt, line 125 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi8KrRuEAXbs0lhcx1N:-MiTJiFz5-Yo97EEJPgU:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a1db03bbe1cbb806d9c58e1f179cde80b318bb83/src/test/kotlin/org/wfanet/measurement/consent/crypto/SignaturesTest.kt#L125)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you can just write `assertFailsWith<DataFailsSignatureValidation> { outFlow2.collect() }`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-08-31 22:49 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 6 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt, line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTNrnTE6yFpZFaI_TI:-MiTNrnTE6yFpZFaI_TJ:b-yp3hik) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt#L57)):*
> ```Kotlin
> ): Pair<Blob, ByteString> {
>   val (contentFlow, deferredSig) = privateKey.signFlow(cert, content)
>   val resultFlow = this.createBlob(blobKey = blobKey, content = contentFlow)
> ```

Rename to `blob`?
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTNxuH7-U1v8oK53sC:-MiTNxuH7-U1v8oK53sD:b-3zkdyv) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L39)):*
> ```Kotlin
>  */
> fun PrivateKey.sign(certificate: X509Certificate, data: ByteString): ByteString {
>   val deferredSig = this.signFlow(certificate, flow { emit(data) })
> ```

`flowOf(data)`
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTO4IqEKYZRwFHBb4f:-MiTO4IqEKYZRwFHBb4g:bgdb841) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L43)):*
> ```Kotlin
>   runBlocking {
>     deferredSig.first.collect()
>     signature = deferredSig.second.await()
> ```

You should be able do:

```
return runBlocking {
  deferredSig.first.collect()
  deferredSig.second.await()
}
```
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 75 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTOEVU3raFi9wabNA3:-MiTOEVU3raFi9wabNA4:b-3zkdyv) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L75)):*
> ```Kotlin
>  */
> fun X509Certificate.verifySignature(data: ByteString, signature: ByteString): Boolean {
>   val resultFlow = this.verifySignedFlow(flow { emit(data) }, signature, "File")
> ```

`flowOf(data)`
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTOTCz-9DE-7MmwVXN:-MiTOTCz-9DE-7MmwVXO:b-ho0f2q) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L102)):*
> ```Kotlin
>   data: Flow<ByteString>,
>   signature: ByteString,
>   blobKey: String
> ```

`blobKey` is only used in the exception? I'd just remove it from the exception message -- callers can always attach more context if needed


<!-- Sent from Reviewable.io -->

2021-09-01 00:30 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @efoxepstein and @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt, line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTNrnTE6yFpZFaI_TI:-MiTkcWe6edqdrmKa1tl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/client/storage/Storage.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Rename to `blob`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 39 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTNxuH7-U1v8oK53sC:-MiTkBBt8YcD00BkTB9l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L39)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`flowOf(data)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTO4IqEKYZRwFHBb4f:-MiTkMbg6kSuOO6Uzqwx:bw2gmnf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You should be able do:

```
return runBlocking {
  deferredSig.first.collect()
  deferredSig.second.await()
}
```
</blockquote></details>

Neat. Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 75 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTOEVU3raFi9wabNA3:-MiTkP71CPwDYT9VGa8T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`flowOf(data)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTOTCz-9DE-7MmwVXN:-MiTjhn99xcaCSZxrVtf:b-3j4jod) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`blobKey` is only used in the exception? I'd just remove it from the exception message -- callers can always attach more context if needed
</blockquote></details>

Gotcha, done.


<!-- Sent from Reviewable.io -->

2021-09-01 16:51 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 3 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTO4IqEKYZRwFHBb4f:-MiXFrV56fqvb1Ymiil5:b-v7gid6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L43)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Neat. Done.
</blockquote></details>

Even more readable might be:

```
val (flow, signature) = signFlow(certificate, flowOf(data))
return runBlocking {
  flow.collect()
  signature.await()
}
```
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTOTCz-9DE-7MmwVXN:-MiXGEb5-svrdUzYopag:bqk7hmq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L102)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Gotcha, done.
</blockquote></details>

I don't see any changes here yet


<!-- Sent from Reviewable.io -->

2021-09-01 17:38 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTO4IqEKYZRwFHBb4f:-MiXR0oO8XhkFELqmb-l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Even more readable might be:

```
val (flow, signature) = signFlow(certificate, flowOf(data))
return runBlocking {
  flow.collect()
  signature.await()
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiTOTCz-9DE-7MmwVXN:-MiXR1gW2kCCj0LY2dkN:bigbr2r) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/a0fb866a56d036caac4ad32aedee7d69f04b6635/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't see any changes here yet
</blockquote></details>

Whoops, sorry, fixed. Actually done now.


<!-- Sent from Reviewable.io -->

2021-09-01 17:56 UTC, efoxepstein approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-01 19:22 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r1, 3 of 8 files at r4, 3 of 4 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @jonmolle, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi7gqJMCs7YWihNY2Hr:-MiXe92-2zQdGn9T6rTL:b8bv3g1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4e6d9fa7214c2d6473544afe2b78a694957236fc/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L46)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

I've added helper extensions StorageClient.createSignedBlob and StorageClient.Blob.verifiedRead that invoke these. I have a PR in panel-exchange to make a wrapper that basically forces all I/O to use them (or will, the actual r/w functions are stubs right now).

I don't really understant the reason for different functions for model and data providers. If everyone is using StorageClient as the abstract interface they can implement whichever (even custom) client without these even needing to be aware what's going on. The panel-exchange wrapper will have to be a bit more clever (only in where to read and write the signatures from), but I can't see how any specific underlying client would affect that (although if I'm missing something here, or in that PR, I'm happy to update it).  
</blockquote></details>

Going ahead and making this comment non-blocking for now since I don't want things to be blocked forever, but I'd really like to get a better understanding of how consent signaling applies for panel exchange and why this functionality should be in consent-signaling-client.

My initial understanding was that this client was for consent signaling within the CMMS public API. Signature utilities were put into this repo (rather than common-jvm) because consent signaling was supposedly the **only** place we're doing manual signing/verification (the non-manual case being the TLS implementation). Since panel match is another place where we deal with signatures, it appears to me that the previous assumption doesn't hold and that the signature and blob store utils should be moved to common-jvm.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 90 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiXkxGyAfPm7pZVRPo2:-MiXkxGyAfPm7pZVRPo3:bwaiafe) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2c5c48ad6b0d4262bc3266fe1bced7b22dd2afea/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L90)):*
> ```
> Verifies
> ```
This doesn't verify, but rather returns a flow that verifies. This is technically a custom flow operator similar to [filter](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/filter.html) or [map](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/map.html), and should be documented similarly.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 94 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiXeX425N6EkVqoEl9M:-MiXeX425N6EkVqoEl9N:b-d50ws4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2c5c48ad6b0d4262bc3266fe1bced7b22dd2afea/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L94)):*
> ```
>  this will throw an [IllegalArgumentException].
> ```
Isn't it an `InvalidSignatureException` instead? Also, make it more clear that the exception isn't thrown by this function (i.e. don't say 'this will throw").
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 96 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiXi_laEBu6vCAIs0E7:-MiXi_laEBu6vCAIs0E8:b-9omb8q) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2c5c48ad6b0d4262bc3266fe1bced7b22dd2afea/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L96)):*
> ```
> @Throws(InvalidSignatureException::class)
> ```
This annotation is used to mark the function as throwing this exception when it's called from Java code. It's
1. Inaccurate, as this function doesn't throw the exception.
2. Unnecessary, since coroutine flow functions don't make sense to call from Java. We don't intend this Kotlin library to be called from Java at all.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 104 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiXj6TS5B5DuEoIigX3:-MiXj6TS5B5DuEoIigX4:b-gdbmhp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2c5c48ad6b0d4262bc3266fe1bced7b22dd2afea/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L104)):*
> ```Kotlin
> 
>   verifier.initVerify(this)
>   return data.onEach { verifier.update(it.asReadOnlyByteBuffer()) }.onCompletion {
> ```

I think you want to check whether the exception passed to onCompletion is null, indicating that the flow is already cancelled/failed. ([`onCompletion`](https://kotlin.github.io/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.flow/on-completion.html) kind of acts like a `finally` block)
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt, line 19 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiXlwGjBT0lEGQDcFGA:-MiXlwGjBT0lEGQDcFGB:b13rgjq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/ed2b03e0825f1a610132065fa87fdd72335ff721/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt#L19)):*
> ```
> "File signature is invalid or missing."
> ```
Don't give a default message. This part is inherent to the exception type and should be in the KDoc for the exception.

Make sure anyone throwing this can instead pass their own message, ideally supporting lazy evaluation. See [KingdomInternalException](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2adbe1889645b43fd8d001babd583cf8054f199c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt) for an example.


<!-- Sent from Reviewable.io -->

2021-09-01 23:06 UTC, efoxepstein approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 6 unresolved discussions (waiting on @jonmolle and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-09-02 18:45 UTC, SanjayVas requested changes
> Reviewed 1 of 8 files at r4, 1 of 2 files at r8, 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 4 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 41 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MibkC_d8ZxZv_sXVg5p:-MibkC_d8ZxZv_sXVg5q:b4vmxwv) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L41)):*
> ```Kotlin
> fun PrivateKey.sign(certificate: X509Certificate, data: ByteString): ByteString {
>   val (flowResult, deferredSig) = this.signFlow(certificate, flowOf(data))
>   return runBlocking {
> ```

I think these are sufficiently different that we don't need the non-flow version to call the flow version. Wrapping in a flow here and forcing use of coroutines seems like unnecessary overhead.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 76 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mibkq980Jlp_RygaVNG:-Mibkq980Jlp_RygaVNH:b-40ykmq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L76)):*
> ```Kotlin
>   val resultFlow = this.verifySignedFlow(flowOf(data), signature)
>   return try {
>     runBlocking { resultFlow.collect() }
> ```

Same here. Just keep the flow and non-flow paths separate, even if it does mean a little duplication.

In general, having to catch an exception like this is a code smell. You generally want your exception version of a function to wrap your boolean version and not the other way around, partially due to the wasted overhead of throwing an exception. Since in this case it's not possible, it's an indication that two separate paths may be better.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/BUILD.bazel, line 6 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mibj_Gn0Htbn_DNie5m:-Mibj_Gn0Htbn_DNie5n:bubrd50) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/BUILD.bazel#L6)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "exceptions",
> ```

Name this "exception" to match the package name, making it the default target for the package.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt, line 33 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiblNuQAPA9G8V6MkPg:-MiblNuQAPA9G8V6MkPh:b-xrjfnm) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt#L33)):*
> ```Kotlin
>   }
> 
>   enum class Code {
> ```

1. You only need something like this if you need the caller to be able to distinguish the conditions. Otherwise, a message is fine.
2. The two ways to do such machine-readable differentiation is a code enum like this, or an inheritance hierarchy. Anything referencing blob storage probably doesn't belong in a generic InvalidSignatureException.


<!-- Sent from Reviewable.io -->

2021-09-02 19:51 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 41 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MibkC_d8ZxZv_sXVg5p:-Mic0RAB0bmw9fyxXbSY:b4nmnl0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think these are sufficiently different that we don't need the non-flow version to call the flow version. Wrapping in a flow here and forcing use of coroutines seems like unnecessary overhead.
</blockquote></details>

I had that initially, but was asked to change it and didn't really feel strongly one way or the other. Happy to revert back.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 76 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mibkq980Jlp_RygaVNG:-Mic0XNA09E6lxMnodDc:bovduqc) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here. Just keep the flow and non-flow paths separate, even if it does mean a little duplication.

In general, having to catch an exception like this is a code smell. You generally want your exception version of a function to wrap your boolean version and not the other way around, partially due to the wasted overhead of throwing an exception. Since in this case it's not possible, it's an indication that two separate paths may be better.
</blockquote></details>

Same as above, done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/BUILD.bazel, line 6 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mibj_Gn0Htbn_DNie5m:-Mic-TyO30feFq9Nb24G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/BUILD.bazel#L6)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Name this "exception" to match the package name, making it the default target for the package.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt, line 33 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MiblNuQAPA9G8V6MkPg:-Mic-VacCO-oCoVwEM8s:bwad6bp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b20fd9f281b4eaa176f94c32c5d7eb5963cde004/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. You only need something like this if you need the caller to be able to distinguish the conditions. Otherwise, a message is fine.
2. The two ways to do such machine-readable differentiation is a code enum like this, or an inheritance hierarchy. Anything referencing blob storage probably doesn't belong in a generic InvalidSignatureException.
</blockquote></details>

That's fair. I was originally going to just give a generic message, but I thought it might be useful for someone catching to know the difference to potentially handle the error differently. Thinking about it a bit more, though, I don't think it matters (as the task step will be a failure and unable to be retried in either case).

I initially thought that the signature being missing could be a wait-and-retry case in the case where an output has been written and somehow recognized by a downstream input task while the signature (which requires a full run through the flow to create) is still in progress. I think there's a way to avoid that race condition elsewhere, though.

As the comments are part of the enum that's been removed, I think part 2 is a bit moot.


<!-- Sent from Reviewable.io -->

2021-09-02 20:44 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt, line 22 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicEmMvEQuMDiapFv3b:-MicEmMvEQuMDiapFv3c:b-sfxanx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt#L22)):*
> ```Kotlin
>  * for the data or can't be found at all.
>  */
> class InvalidSignatureException(message: String?) : Exception(message)
> ```

Don't call the super string constructor with a null string. You want separate constructor overloads here which call the separate super constructors.


<!-- Sent from Reviewable.io -->

2021-09-02 20:46 UTC, efoxepstein requested changes
> Reviewed 5 of 5 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 3 unresolved discussions (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/storage/BUILD.bazel, line 10 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicFDlSDZ4B_y3ZuGc6:-MicFDlSDZ4B_y3ZuGc7:b-2zvtm0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/client/storage/BUILD.bazel#L10)):*
> ```Starlark
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/consent/crypto:signatures",
>         "//src/main/kotlin/org/wfanet/measurement/consent/crypto/exception:exception",
> ```

You can chop off the `:exception` suffix now
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel, line 9 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicFJou71mCG5LsvD_U:-MicFJou71mCG5LsvD_V:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel#L9)):*
> ```Starlark
>     srcs = ["Signatures.kt"],
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/consent/crypto/exception:exception",
> ```

Ditto


<!-- Sent from Reviewable.io -->

2021-09-02 23:04 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: 6 of 9 files reviewed, 3 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/storage/BUILD.bazel, line 10 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicFDlSDZ4B_y3ZuGc6:-MiccIzG1K4uBZ3Y7fRr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/client/storage/BUILD.bazel#L10)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can chop off the `:exception` suffix now
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel, line 9 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicFJou71mCG5LsvD_U:-Micc6RVCOzrb04xZz7d:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/crypto/BUILD.bazel#L9)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt, line 22 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicEmMvEQuMDiapFv3b:-MichqZZDqdjhDbBcMeg:b-9752eo) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't call the super string constructor with a null string. You want separate constructor overloads here which call the separate super constructors.
</blockquote></details>

Done, although I'd rather force someone to pass a message than do nothing. Is there a specific issue here that can happen? It seems like a null string behaves the same as an empty constructor.


<!-- Sent from Reviewable.io -->

2021-09-02 23:48 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt, line 22 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicEmMvEQuMDiapFv3b:-MictV4a5FPFwaobDBIz:bcp374d) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt#L22)):*
> Done, although I'd rather force someone to pass a message than do nothing.

SGTM

> Is there a specific issue here that can happen? It seems like a null string behaves the same as an empty constructor.

While this is true, I don't believe it's explicitly documented.


<!-- Sent from Reviewable.io -->

2021-09-03 14:58 UTC, efoxepstein approved these changes
> Reviewed 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-03 17:59 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt, line 22 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-MicEmMvEQuMDiapFv3b:-MignzslC6YTHrvnfqsR:b-yk3j3b) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7709ce46b5cdb5470abe3774b47b1244dc61c9e2/src/main/kotlin/org/wfanet/measurement/consent/crypto/exception/InvalidSignatureException.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Done, although I'd rather force someone to pass a message than do nothing.

SGTM

> Is there a specific issue here that can happen? It seems like a null string behaves the same as an empty constructor.

While this is true, I don't believe it's explicitly documented.
</blockquote></details>

Gotcha, I was just going by the signature in intellij, so not exactly the most canonical source


<!-- Sent from Reviewable.io -->

2021-09-03 18:41 UTC, jonmolle reviewed
Note: Since this is going to be migrated in a subsequent PR, I've delayed doing this here.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-:-MigxSJa7PDPVMHjl1pl:b9keot)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-03 18:41 UTC, jonmolle reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-:-MigxtgDAm3aLT8EwIQ9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-03 18:46 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-07 23:05 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2021-09-08 03:08 UTC, stevenwarejones approved these changes
> Reviewed 1 of 5 files at r10, 3 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi7gqJMCs7YWihNY2Hr:-Mj2MeOA33CMVrmnaWOC:bj3o4rh) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4e6d9fa7214c2d6473544afe2b78a694957236fc/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L46)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

Happy to, Done
</blockquote></details>

I've been thinking about this more and I think it falls under the category of consent signaling. Just as a MC might sign a measurement request, the panel provider can sign a Event Lookup Query. I would like to keep it in consent signaling.


<!-- Sent from Reviewable.io -->

2021-09-08 17:23 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/16#-Mi7gqJMCs7YWihNY2Hr:-Mj5QisJ7rZqkTN4GFd1:bj33my6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4e6d9fa7214c2d6473544afe2b78a694957236fc/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I've been thinking about this more and I think it falls under the category of consent signaling. Just as a MC might sign a measurement request, the panel provider can sign a Event Lookup Query. I would like to keep it in consent signaling.
</blockquote></details>

@stevenwarejones @sanjayvas can we have a chat on Slack or Dev Connect (separately from this PR) to figure out the scope of consent-signaling?


<!-- Sent from Reviewable.io -->

2021-09-08 17:25 UTC, merged