Break apart createParticipationSignature into two functions
world-federation-of-advertisers/consent-signaling-client pull request #22
Opened 2021-09-17 20:01 UTC by corbantek

- Create two functions from createParticipationSignature
  - processRequisition - decrypts requisitionSpec from the requistion and generates the requisitionFingerprint (and returns both)
  - signRequisitionFingerprint - signs the requisitionFingerprint
- Fix a bug in createParticipationSignature().
  - The encrypteRequisitionSpec is an encrypted signedData, not a requisitionSpec.
- Update to use HexString from jvm-common instead of Base64

2021-09-17 20:10 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpN0x8AQLqoRPlfPkj:-MjpN0x8AQLqoRPlfPkk:b-7jrt72) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L47)):*
> ```
> processRequisitionSpec
> ```

not sure what is the best name here.
processRequisition?
processRequisitionSpecAndCreateParticipationSignature?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpLvSt1n85JT6yskSu:-MjpLvSuEntTveZcoRQn:b-a4ylpw) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L52)):*
> ```
>  Pair<RequisitionSpec, ByteString>
> ```

nit: I am not objecting to use Pair<> here, but I remember people asked me to use Data Class instead of Pair<> whenever possible for better readability. 

@sanjayvas  any comment?


<!-- Sent from Reviewable.io -->

2021-09-17 20:13 UTC, stevenwarejones approved these changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpLvSt1n85JT6yskSu:-MjpNlOP1Y4HgkF8v3UO:brn2xfl) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L52)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  Pair<RequisitionSpec, ByteString>
> ```

nit: I am not objecting to use Pair<> here, but I remember people asked me to use Data Class instead of Pair<> whenever possible for better readability. 

@sanjayvas  any comment?

</blockquote></details>

yeah, a dataclass would be more meaningful `processedRequisitionSpec`


<!-- Sent from Reviewable.io -->

2021-09-17 21:27 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpN0x8AQLqoRPlfPkj:-MjpdWf38sbr5K_yBsof:b-i1dqpz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L47)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> processRequisitionSpec
> ```

not sure what is the best name here.
processRequisition?
processRequisitionSpecAndCreateParticipationSignature?
</blockquote></details>

Yeah I'm completely open to other names, I did processRequisitionSpec since thats what its operating on, but I'm not married to anything at the moment.  I'll let other suggestions come in...
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpLvSt1n85JT6yskSu:-Mjpdn2yCWOXQq6R-T4_:b-c53dg7) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah, a dataclass would be more meaningful `processedRequisitionSpec`
</blockquote></details>

I can change it, I just liked how Kotlin supports it somewhat natively on the left hand side of the equals (sort of like go syntax) when actually calling it.


<!-- Sent from Reviewable.io -->

2021-09-17 21:29 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: all files reviewed, 7 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[WORKSPACE, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-Mjpc0YM1TVLfWMNsWvr:-Mjpc0YM1TVLfWMNsWvs:b-683m69) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/WORKSPACE#L29)):*
> ```
> "common-jvm-0.11.0"
> ```
Why not use the latest version (0.13.0)?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpdKM77qpz0vypa4_u:-MjpdKM77qpz0vypa4_v:b14ca12) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L39)):*
> ```
>  * Process Requisition Spec will decrypt the RequistionSpec from the [requisition] and generate the
>  * RequisitionFingerprint, which is the concatenation of a. The SHA-256 hash of the encrypted
>  * RequisitionSpec b. The ParticipantListHash c. The serialized MeasurementSpec
> ```
nit: summary fragment should not be a complete sentence.

See https://developer.android.com/kotlin/style-guide#summary_fragment
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-Mjpc7gq2INt1_n1NAkX:-Mjpc7gq2INt1_n1NAkY:b-x2b353) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L45)):*
> ```Kotlin
>  * initially received by the data provider.
>  *
>  * A Pair of decrypted RequisitionSpec and RequisitionFingerprint are returned
> ```

Use KDoc `@return` tag.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpLvSt1n85JT6yskSu:-MjpcIVCChPSmfa9KbbX:ba59w3s) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah, a dataclass would be more meaningful `processedRequisitionSpec`
</blockquote></details>

+1 to data class for improved readability. Pairs are fine when temporary/intermediate, e.g. when using `zip` as a step to converting parallel collections into a map.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpcxCB-uefI67FStNs:-MjpcxCB-uefI67FStNt:bp9giil) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L68)):*
> ```Kotlin
>       .concat(requireNotNull(requisition.measurementSpec.data))
>   return Pair(requisitionSpec, requisitionFingerprint)
> }
> ```

nit: blank line between functions
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 156 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-Mjpdp1l7-liEYsEBfgm:-Mjpdp1l7-liEYsEBfgn:bytfuno) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L156)):*
> ```
> HexString(requistionFingerprint).value
> ```
`HexString` is intended to be a stronger-typed alternative to strings. They are also comparable. Therefore, this can be written as 
```
assertThat(HexString(requisitionFingerprint)).isEqualTo(HexString("4B4..."))
```


<!-- Sent from Reviewable.io -->

2021-09-17 22:34 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: all files reviewed, 7 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpN0x8AQLqoRPlfPkj:-Mjpt8zT1DVwMN8M0D-O:bfemlho) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L47)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Yeah I'm completely open to other names, I did processRequisitionSpec since thats what its operating on, but I'm not married to anything at the moment.  I'll let other suggestions come in...
</blockquote></details>

It also touches the measurementSpec, a little bit.


<!-- Sent from Reviewable.io -->

2021-09-21 15:13 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[WORKSPACE, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-Mjpc0YM1TVLfWMNsWvr:-Mk7jVM1-Y2AhPNap35r:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/WORKSPACE#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "common-jvm-0.11.0"
> ```
Why not use the latest version (0.13.0)?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpdKM77qpz0vypa4_u:-Mk7lyfI8-qeicD8uYRy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>  * Process Requisition Spec will decrypt the RequistionSpec from the [requisition] and generate the
>  * RequisitionFingerprint, which is the concatenation of a. The SHA-256 hash of the encrypted
>  * RequisitionSpec b. The ParticipantListHash c. The serialized MeasurementSpec
> ```
nit: summary fragment should not be a complete sentence.

See https://developer.android.com/kotlin/style-guide#summary_fragment
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-Mjpc7gq2INt1_n1NAkX:-Mk7m-Wq754S-zhjqK-S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc `@return` tag.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpN0x8AQLqoRPlfPkj:-Mk7m0nl23cEcSqNUy_M:b-l2dx1a) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L47)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

It also touches the measurementSpec, a little bit.
</blockquote></details>

Went with `decryptRequisitionSpecAndGenerateRequisitionFingerprint` although it's long it's descriptive. Open to change...
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpLvSt1n85JT6yskSu:-Mk7mBAk4yHohWYfDtQ9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

+1 to data class for improved readability. Pairs are fine when temporary/intermediate, e.g. when using `zip` as a step to converting parallel collections into a map.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpcxCB-uefI67FStNs:-Mk7mKR51w_vWkGRrF9k:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: blank line between functions
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 156 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-Mjpdp1l7-liEYsEBfgm:-Mk7mtfy6DqkUSVkA0S0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> HexString(requistionFingerprint).value
> ```
`HexString` is intended to be a stronger-typed alternative to strings. They are also comparable. Therefore, this can be written as 
```
assertThat(HexString(requisitionFingerprint)).isEqualTo(HexString("4B4..."))
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-21 15:24 UTC, wangyaopw approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: all files reviewed, 4 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpN0x8AQLqoRPlfPkj:-Mk7x6RsDPQ2IujPBxCw:b-nq7k77) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L47)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Went with `decryptRequisitionSpecAndGenerateRequisitionFingerprint` although it's long it's descriptive. Open to change...
</blockquote></details>

nit: participationFingerprint


<!-- Sent from Reviewable.io -->

2021-09-21 15:24 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: all files reviewed, 4 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-21 15:45 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: all files reviewed, 4 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22#-MjpN0x8AQLqoRPlfPkj:-Mk816cFBR7yoaXTl7BD:bdw1vlo) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/fccac391f089cb25568f551f9941384def8d85d8/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L47)):*
> EdpParticipationSignature
oh, that makes sense,


<!-- Sent from Reviewable.io -->

2021-09-21 15:45 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-21 17:15 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/22)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-21 22:08 UTC, merged