Implement initial keystore, crypto, and signage for consent signaling
world-federation-of-advertisers/consent-signaling-client pull request #4
Opened 2021-06-30 19:41 UTC by corbantek

Duchy Client
------------
- The following has been implemented
  - Functions
    - `VerifyEDPSignature`
    - `SignAndEncryptResult`
  - Use Case
    - Under test there is DuchyClientTest thats shows the possible use
case of a caller to these functions

Components
----------
`crypto` package contains the basic interfaces for crypto (encrypt/decrypt).
`crypto` also contains the subpackage `signage` for (sign and verify), and
`keystore` for storing private keys

Crypto Interface
----------------
A simple interface to encrypt and decrypt data (will eventually use Tink under
the covers)

Signage Interface
-----------------
A simple interface to sign and veriy signatures of data

Keystore
--------
This abstract class can be implemented for various types of keystorage (and
eventually KMS).  Currently there is a sample In-Memory keystore to be used
for testing and bringup.  The current design is client can store private key's
in the keystore can reteive an PrivateKeyHandle to the private key (note the object
does not actually contain the private key) that contains a refrence back to
keystore that was used.

Only the `crypto` and `signage` interfaces can access the actual underlying private
key of the PrivateKeyHandle

TODOs
-----
- Unit tests will be writen once this design approach is approved
- Tink encrypt/decrypt will be written
- "Better" KeyStore KMS implementations

2021-06-30 23:02 UTC, SanjayVas requested changes
> Reviewed 5 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 5 of 21 files reviewed, 10 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, and @stevenwarejones)

___
*[WORKSPACE, line 182 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdTx4AV7sg_o5w87i0v:-MdTx4AV7sg_o5w87i0w:b-54pido) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/WORKSPACE#L182)):*
> ```
> wfa_measurement_api_proto
> ```
You want to keep the import name for a workspace consistent everywhere. This name should match the name defined in the WORKSPACE file of the one you're importing.

If we're going to rename this, we should do it across all repos.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3ZbvAwz0d0VXYiMl:-MdU3ZbvAwz0d0VXYiMm:bypaka4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L9)):*
> ```
> ByteArray
> ```
Prefer immutable types. We use `com.google.protobuf.ByteString` as our immutable collection of bytes.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3myp2NHcAsPIRFmL:-MdU3myp2NHcAsPIRFmM:b-7bs3qe) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L12)):*
> ```
> "SHA-256"
> ```
Extract constant
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3oW1972LQS_9wGn7:-MdU3oW1972LQS_9wGn8:b6eg569) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L12)):*
> ```
> md
> ```
Use descriptive variable names.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU4nDP8m35XekZwdm9:-MdU4nDP8m35XekZwdmA:b-p5d2wk) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L15)):*
> ```
> .map { String.format("%02X", it) }
> ```
What is this transformation for? Why can't we use the ByteArray returned by `digest`directly?
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU5SWZAyAXFNR8hG2d:-MdU5SWZAyAXFNR8hG2e:b-fz5dqp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L8)):*
> ```
> Crypto
> ```
nit: `Crypto` is a bit general, where this is specifically for encryption/decryption. Perhaps `Cryptor` or `Cipher`? Could even prefix with `Hybrid` to be clear we're always doing hybrid encryption.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6AoM35HRDPNnp-95:-MdU6AoM35HRDPNnp-96:b-7e1wlr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L12)):*
> ```
> publicKey: EncryptionPublicKey
> ```
We only use hybrid encryption, not purely asymmetric. This means that encrypting requires the sender's private key and the receiver's public key.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6_cx2JX3EXfxZ2oc:-MdU6_cx2JX3EXfxZ2od:b-w8r1lx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L17)):*
> ```
> privateKeyHandle: PrivateKeyHandle
> ```
Same here: re decryption, except that you need the sender's public key and the receiver's private key.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/PrivateKeyHandle.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU82TR5-q_lhLpihOm:-MdU82TR5-q_lhLpihOn:b-44vck1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/PrivateKeyHandle.kt#L36)):*
> ```
> toJavaPrivateKey
> ```
I don't think this method can always be safely called. There's not a Java security implementation for each key type we may want to use, just the ones for signatures. Meaning there might not be a valid Java key algorithm string for each PrivateKeyHandle.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6zZC1M5wi8Pyb2bt:-MdU6zZC1M5wi8Pyb2bu:b-1s27r5) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt#L8)):*
> ```
> TinkCrypto
> ```
I don't think the engine is the operative difference between the implementations, but rather which cipher suite is being used. I think we're fine assuming Tink as an implementation detail at this layer.

@kungfucraig to make sure we're abstracting at the right layer.


<!-- Sent from Reviewable.io -->

2021-06-30 23:03 UTC, SanjayVas commented
Did a partial first pass on comments. Need to take a deeper look at the keystore/handle parts.

2021-07-02 03:55 UTC, corbantek reviewed
@sanjayvas I think my only question now is related to how Tink does Hybrid Encryption.  Tink is very picky about its key origins and it seems to ONLY want keys created inside of Tink (there isn't any good way to import non Tink keys).

I guess my question is, should I create a utility in this repo that allows clients to generate the keys from inside Tink (abstracted so they don't know its Tink).   I think my missing knowledge here is where y'all had assumed the keys would be created?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-:-Md_IBSe3OcBoh5JxMlA:b-3sfy1o)* status: 5 of 21 files reviewed, 10 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 182 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdTx4AV7sg_o5w87i0v:-Md_EQuD9SG9fxtxDFN8:b-996b5r) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/WORKSPACE#L182)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> wfa_measurement_api_proto
> ```
You want to keep the import name for a workspace consistent everywhere. This name should match the name defined in the WORKSPACE file of the one you're importing.

If we're going to rename this, we should do it across all repos.
</blockquote></details>

Sure I can change it back to `wfa_measurement_proto` but my original thinking was to make this more descriptive since the current names could be consfusing.  I'm importing from both `cross-media-measurement-api` and `cross-media-measurement` and today the current mapping being used is this

`cross-media-measurement-api`--> `wfa_measurement_proto`
`cross-media-measurement` --> `wfa_measurement_system`

I'll fix mine to be more standard.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3ZbvAwz0d0VXYiMl:-Md_FkjJ3AJhJBdzYwac:b-932b00) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ByteArray
> ```
Prefer immutable types. We use `com.google.protobuf.ByteString` as our immutable collection of bytes.
</blockquote></details>

Sure, but just to be clear should I update all references of ByteArray to ByteString (where applicable)?
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3myp2NHcAsPIRFmL:-Md_G0MqCmkc5g38oKYx:bebrt1w) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "SHA-256"
> ```
Extract constant
</blockquote></details>

Will do
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3oW1972LQS_9wGn7:-Md_H2f7EI23vRyOzXsM:bebrt1w) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> md
> ```
Use descriptive variable names.
</blockquote></details>

Will do
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU4nDP8m35XekZwdm9:-Md_H43G6wJhRw4DvNec:b-60pp98) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> .map { String.format("%02X", it) }
> ```
What is this transformation for? Why can't we use the ByteArray returned by `digest`directly?
</blockquote></details>

Good catch and you're correct, its unneeded.  I think I pulled this from my sample runner where I was doing some String to ByteArray manipulation. Its not needed and I'll remove.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU5SWZAyAXFNR8hG2d:-Md_HKS_6lPwFOGBGyVJ:bki6c3u) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Crypto
> ```
nit: `Crypto` is a bit general, where this is specifically for encryption/decryption. Perhaps `Cryptor` or `Cipher`? Could even prefix with `Hybrid` to be clear we're always doing hybrid encryption.
</blockquote></details>

I agree, just couldn't think of a better name at the time.

I really like your suggestion of `HybridCryptor`
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6AoM35HRDPNnp-95:-Md_HYke5R-jCgCO8bQk:bqgw2c6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> publicKey: EncryptionPublicKey
> ```
We only use hybrid encryption, not purely asymmetric. This means that encrypting requires the sender's private key and the receiver's public key.
</blockquote></details>

Tink is weird how it does the Hybrid Encryption.  I *think* what its doing is it only needs the public key handle (for encrypting) or private key handle (for decrypting) and the hybrid part is stored in the encrypted data itself.

Two good links: 
https://developers.google.com/tink/exchange-data
https://github.com/google/tink/blob/master/docs/JAVA-HOWTO.md#hybrid-encryption

But this does bring up a good point.  I think Tink's keys are somewhat incompatible with traditional openssh keys, so I probably won't be able to use this `EncryptionPublicKey` protobuf and may need to roll my own (or we need rethink how we pass these keys around).   Tink really wants us to use the `JsonKeysetReader` or we could implement our own Reader/Writer, but I still don't think it will conform to any standard DER formats (that we use for everything else + signatures)...
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6_cx2JX3EXfxZ2oc:-Md_HkYgEtWsEALRYcQx:begieqs) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> privateKeyHandle: PrivateKeyHandle
> ```
Same here: re decryption, except that you need the sender's public key and the receiver's private key.
</blockquote></details>

See comment above...
___
*[ [...]

2021-07-06 21:45 UTC, stevenwarejones reviewed
> Reviewed 2 of 21 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 5 of 21 files reviewed, 11 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6AoM35HRDPNnp-95:-MdxahQf504vHEnmBOdw:b-ht7n4e) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Tink really wants us to use the JsonKeysetReader or we could implement our own Reader/Writer, but I still don't think it will conform to any standard DER formats (that we use for everything else + signatures)...

I believe there's a PEM keyset reader in the works, but no idea when it's coming. (PEM is just base64-encoded DER plus header and footer). We may need to add our own DER keyset reader for public keys. Since private keys will get read through Tink's cloud keystore interface, I think we'll already be able to get them as keysets.

> Tink is weird how it does the Hybrid Encryption. I think what its doing is it only needs the public key handle (for encrypting) or private key handle (for decrypting) and the hybrid part is stored in the encrypted data itself.

So looking at the [underlying code used to construct a HybridEncrypt primitive](https://github.com/google/tink/blob/cb380f363b9ed33c75ba19da4a2e491fabe87ae6/java_src/src/main/java/com/google/crypto/tink/hybrid/EciesAeadHkdfPublicKeyManager.java), you're using the recipients public key. Similarly when constructing a HybridDecrypt primitive, you're using the recipient's private key. I *think* the example just happens to be generating a keypair for the recipient, whereas you'd normally have the recipient's public key already. It looks like the issue is that hybrid encrypt primitive *always* generates a new ephemeral sender keypair, and then includes the sender public key as a prefix/header. The private key gets thrown away since it's ephemeral.

I think we'll have to figure out our options: 1. Is there a safe route to reusing a sender key for multiple ciphertexts, or 2. Do we need to redesign our consent signaling protocol to have truly ephemeral sender keys. I'm thinking we most likely need to do number 2, which means that the per-measurement public key is only used as a recipient key for the result rather than as the sender key for encrypting the requisition specs. Each requisition spec would instead be encrypted with a separate ephemeral public key.
</blockquote></details>

I'm a little confused by your comment @sanjayvas .... I thought hybrid encryption generally worked by only inputting a public key to the encryption library. The library, itself, then generates a symmetric key, encrypts everything with the symmetric key, and then encrypts the symmetric key with the asymmetric key. If thats the case, then how Kyle has it is correct.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt, line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mdxf9DxCNAbTfop0oHD:-Mdxf9DyB8IPpjTG3f2v:b-39409f) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt#L90)):*
> ```Kotlin
>    */
>   private fun generateSaltLength(keySize: Int): Int {
>     return ((keySize + 6) / 8) - 32 - 2
> ```

Please add a comment about the math used here


<!-- Sent from Reviewable.io -->

2021-07-07 16:38 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 5 of 21 files reviewed, 12 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me0nl2t14PcuIKj0N8C:-Me0nl2t14PcuIKj0N8D:b555ntk) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt#L30)):*
> ```
> Signature
> ```
You should use [SecurityProvider](https://github.com/world-federation-of-advertisers/common-jvm/blob/f97ad14726a865f50bdd7aed75f8621df5803128/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt) from common-jvm to get instances of Java security types. This ensures that Conscrypt is registered.

Tink Java actually supports signing and verifying signatures. What it doesn't support is interactions with X.509 certificates, meaning it only interacts with the keys. It doesn't handle verification of the certificate chain, nor generating certificates. Up to you how you want to handle the split between Java security and Tink routines for this.


<!-- Sent from Reviewable.io -->

2021-07-07 18:03 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 5 of 21 files reviewed, 12 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6AoM35HRDPNnp-95:-Me16wSMDxA4H7SknSjV:ba5io4q) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L12)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm a little confused by your comment @sanjayvas .... I thought hybrid encryption generally worked by only inputting a public key to the encryption library. The library, itself, then generates a symmetric key, encrypts everything with the symmetric key, and then encrypts the symmetric key with the asymmetric key. If thats the case, then how Kyle has it is correct.
</blockquote></details>

To go to a lower level, the way hybrid encryption works is that you use a key agreement algorithm (such as Diffie-Helman) to generate a shared secret using a private key generated by the sender and a public key from the recipient. This will be the same secret that would be generated by the sender's public key and recipient's private key. You then take that shared secret and run it through a key derivation function (such as HKDF) to get an appropriate symmetric key.

What Kyle has is correct for hybrid encryption best practices, which has the sender key pair be ephemeral and used just for that one encryption. Our current API design instead assumes limited reuse of per-measurement sender key, which should change to follow the best practice.


<!-- Sent from Reviewable.io -->

2021-07-08 05:38 UTC, corbantek reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 2 of 21 files reviewed, 11 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 182 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdTx4AV7sg_o5w87i0v:-Me3UGkQ5kC97T37VuUe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/WORKSPACE#L182)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I agree that the names we have aren't great and should be changed. It's just that we should plan out and do all the renaming at once.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3ZbvAwz0d0VXYiMl:-Me3Uoo9DZSOhqpG20tz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3myp2NHcAsPIRFmL:-Me3UoTV9I_SbsbePM7s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L12)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3oW1972LQS_9wGn7:-Me3Uvr5AtKYGY6Jl-YZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L12)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Will do
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU4nDP8m35XekZwdm9:-Me3V7ub-dbQzKsCKp4m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L15)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Good catch and you're correct, its unneeded.  I think I pulled this from my sample runner where I was doing some String to ByteArray manipulation. Its not needed and I'll remove.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU5SWZAyAXFNR8hG2d:-Me3buEvBzXt48OyN4Fz:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L8)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

I agree, just couldn't think of a better name at the time.

I really like your suggestion of `HybridCryptor`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-07-09 16:46 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 2 of 21 files reviewed, 10 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me0nl2t14PcuIKj0N8C:-MeB9-f1-CEZOMtHyqAm:b6pclir) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Signature
> ```
You should use [SecurityProvider](https://github.com/world-federation-of-advertisers/common-jvm/blob/f97ad14726a865f50bdd7aed75f8621df5803128/src/main/kotlin/org/wfanet/measurement/common/crypto/SecurityProvider.kt) from common-jvm to get instances of Java security types. This ensures that Conscrypt is registered.

Tink Java actually supports signing and verifying signatures. What it doesn't support is interactions with X.509 certificates, meaning it only interacts with the keys. It doesn't handle verification of the certificate chain, nor generating certificates. Up to you how you want to handle the split between Java security and Tink routines for this.

</blockquote></details>

SecurityProvider in common is currently passing around Files. I don't think we want to do it that way. I think one could also argue that common code should be part of consent signaling possibly.

Either way, I suggest leaving as is for now and dealing with later.


<!-- Sent from Reviewable.io -->

2021-07-09 17:51 UTC, SanjayVas requested changes
> Reviewed 3 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 5 of 21 files reviewed, 4 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me0nl2t14PcuIKj0N8C:-MeBLzbL9X-zOGdLMjcw:bysvrc0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

SecurityProvider in common is currently passing around Files. I don't think we want to do it that way. I think one could also argue that common code should be part of consent signaling possibly.

Either way, I suggest leaving as is for now and dealing with later.
</blockquote></details>

`SecurityProvider` should be updated with other overloads. In fact, I have some pending code that does this as it's needed for parsing the expiration dates from certificates in the public API service implementations.

I want to use `SecurityProvider` right away to guarantee that Conscrypt is loaded, as otherwise we could be using outdated implementations that come with JDK 11. See the guidance in https://github.com/google/tink/blob/cb380f363b9ed33c75ba19da4a2e491fabe87ae6/docs/KNOWN-ISSUES.md#java.

This is one of the repos that common-jvm was split out for. That common repo is intended to be depended on by every one of our repos with Kotlin JVM code.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6AoM35HRDPNnp-95:-MeBLLRP6K17r5iYEGhB:b8jjsj4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To go to a lower level, the way hybrid encryption works is that you use a key agreement algorithm (such as Diffie-Helman) to generate a shared secret using a private key generated by the sender and a public key from the recipient. This will be the same secret that would be generated by the sender's public key and recipient's private key. You then take that shared secret and run it through a key derivation function (such as HKDF) to get an appropriate symmetric key.

What Kyle has is correct for hybrid encryption best practices, which has the sender key pair be ephemeral and used just for that one encryption. Our current API design instead assumes limited reuse of per-measurement sender key, which should change to follow the best practice.
</blockquote></details>

PR https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/35 should address the API changes. It means the parameters for this should now be sufficient, though `publicKey` should be `recipientPublicKey` for clarity.


<!-- Sent from Reviewable.io -->

2021-07-09 18:31 UTC, oliver-amzn reviewed
> Reviewed 2 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 7 of 21 files reviewed, 7 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me70i8e6Yg_G_fQ5m0s:-Me70i8e6Yg_G_fQ5m0t:b-9r2sve) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L14)):*
> ```Kotlin
> 
> /**
>  * crypto can encrypt and decrypt data (currently using 'no encryption' implementation, but will
> ```

Is this comment out of date? It references `crypto`
___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me70nKE4nl_j3FCn7HH:-Me70nKF7d0cNybQQlMa:bks8iha) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L17)):*
> ```
> hybridCryptor: HybridCryptor = NoHybridCryptor()
> ```

This doesn't look right (hybridCryptor = NoHybridCryptor) . Should the variable be just `cryptor` or something else? 
___
*[src/main/kotlin/org/wfanet/consentsignaling/client/duchy/DuchyClient.kt, line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me7oDUx2lSZkq_RyayK:-Me7oDUx2lSZkq_RyayL:b-y798oz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/duchy/DuchyClient.kt#L16)):*
> ```
> Duchies'  ...
> ```

--> Duchy's ? 
___
*[src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU3oW1972LQS_9wGn7:-MeAvXX27xRNc97KNcjf:bru8a9y) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/common/HashUtils.kt#L12)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Make this `messageDigest` and not include the algo in the name? 


<!-- Sent from Reviewable.io -->

2021-07-13 03:33 UTC, stevenwarejones reviewed
> Reviewed 2 of 21 files at r1, 3 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 2 of 34 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me70i8e6Yg_G_fQ5m0s:-MeMXDqh7pI8pX5dcF6b:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L14)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Is this comment out of date? It references `crypto`
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me70nKE4nl_j3FCn7HH:-MeMX6Pn3221sWsxBQl_:bjvvkbd) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L17)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> hybridCryptor: HybridCryptor = NoHybridCryptor()
> ```

This doesn't look right (hybridCryptor = NoHybridCryptor) . Should the variable be just `cryptor` or something else? 
</blockquote></details>

The interface is for `HybridCryptor` --- these are just different implementations of hybrid encryption.
___
*[src/main/kotlin/org/wfanet/consentsignaling/client/duchy/DuchyClient.kt, line 16 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me7oDUx2lSZkq_RyayK:-MeMYMdN-ro-64-ejLsr:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/duchy/DuchyClient.kt#L16)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> Duchies'  ...
> ```

--> Duchy's ? 
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6AoM35HRDPNnp-95:-MeMYo-d482llOmdSuFe:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/Crypto.kt#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

PR https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/35 should address the API changes. It means the parameters for this should now be sufficient, though `publicKey` should be `recipientPublicKey` for clarity.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6zZC1M5wi8Pyb2bt:-MeMZ_Kl1w9RbnicthBv:blom9v4) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> TinkCrypto
> ```
I don't think the engine is the operative difference between the implementations, but rather which cipher suite is being used. I think we're fine assuming Tink as an implementation detail at this layer.

@kungfucraig to make sure we're abstracting at the right layer.
</blockquote></details>

renamed this to `ECIESCryptor` - what do you think?
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me0nl2t14PcuIKj0N8C:-MeQT6uK7orY3FSY0Hnw:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/signage/JavaSecuritySignage.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`SecurityProvider` should be updated with other overloads. In fact, I have some pending code that does this as it's needed for parsing the expiration dates from certificates in the public API service implementations.

I want to use `SecurityProvider` right away to guarantee that Conscrypt is loaded, as otherwise we could be using outdated implementations that come with JDK 11. See the guidance in https://github.com/google/tink/blob/cb380f363b9ed33c75ba19da4a2e491fabe87ae6/docs/KNOWN-ISSUES.md#java.

This is one of the repos that common-jvm was split out for. That common repo is intended to be depended on by every one of our repos with Kotlin JVM code.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-13 13:24 UTC, oliver-amzn reviewed
> Reviewed 1 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 3 of 34 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me70nKE4nl_j3FCn7HH:-MeV1CFxEa05jNF-ns7q:b-mxmq9t) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L17)):*
> NoHybridCryptor

Then maybe I'm just taking objection with the name `NoHybridCryptor`. It's a no-op hybrid encryptor, right? Maybe That's what the name should be.


<!-- Sent from Reviewable.io -->

2021-07-13 14:39 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 2 of 34 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me70nKE4nl_j3FCn7HH:-MeVGkbU9pUABCWXw4wh:b-5ubjmq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L17)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> NoHybridCryptor

Then maybe I'm just taking objection with the name `NoHybridCryptor`. It's a no-op hybrid encryptor, right? Maybe That's what the name should be.
</blockquote></details>

This is out-of-date. I changed this to `FakeHybridCryptor` that just reverses the string.


<!-- Sent from Reviewable.io -->

2021-07-13 20:04 UTC, SanjayVas requested changes
> Reviewed 5 of 32 files at r3, 1 of 2 files at r4, 7 of 13 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 15 of 34 files reviewed, 14 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[imports/java/org/mockito/BUILD.bazel, line 4 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWL-w_3hjhSqESjQP_:-MeWL-w_3hjhSqESjQPa:b-ski1ll) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/imports/java/org/mockito/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "mockito",
> ```

You should be able to get this from `@wfa_common_jvm//imports` instead of needing to define it here.
___
*[src/main/kotlin/org/wfanet/consentsignaling/client/BUILD.bazel, line 5 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWMmwNBysu9xGzhzXn:-MeWMmwNBysu9xGzhzXo:b6de81j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/client/BUILD.bazel#L5)):*
> ```
> test_target(":__subpackages__"),
> ```
Probably want this to be `"//visibility:public"` since I assume this is the piece that would be used by other repos.
___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWLT7tD7_ogrIh2Fsg:-MeWLT7tD7_ogrIh2Fsh:b-tot3ch) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

I don't think this is how we want to configure the dependencies.

The cryptor would always depend on the HybridCipherSuite, and I don't think we need an abstraction around signing at all.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/BUILD.bazel, line 9 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWPN2H6-a_QkPNB-i9:-MeWPN2ID_fOGmbA6rFV:bs8o954) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/BUILD.bazel#L9)):*
> ```
> hybrid_encryption
> ```
nit: top-level glob everything target names should match the Bazel package name
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWQskX3ZsdfVxQj6b8:-MeWQskX3ZsdfVxQj6b9:b70k4vg) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt#L23)):*
> ```
> ByteArray
> ```
Use com.google.protobuf.ByteString where possible as an immutable byte collection type.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/BUILD.bazel, line 7 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWS-UV0F0kPG5jqRRi:-MeWS-UV0F0kPG5jqRRj:bsu1k2n) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/BUILD.bazel#L7)):*
> ```
>     testonly = True,
> ```
nit: you put `default_testonly = True` in the `package` declaration instead. This way if you split up the targets, they'll still be testonly.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6zZC1M5wi8Pyb2bt:-MeWQc437VPsIQA0JmjI:b-p4ndnu) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt#L8)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

renamed this to `ECIESCryptor` - what do you think?
</blockquote></details>

It's fine, assuming the intent is to use this for all `HybridCipherSuite` values that use ECIES. Though note that it should be `EciesCryptor` as per https://developer.android.com/kotlin/style-guide#camel_case
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hash/HashUtils.kt, line 20 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWN9pjAVKtsRSFIrBR:-MeWN9pjAVKtsRSFIrBS:bppjvzc) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hash/HashUtils.kt#L20)):*
> ```
> object CommonConstants {
> ```
We don't tend to wrap constants in objects to emulate a namespace. We just rely on the package path.

If you do want to group constants, do so by type (e.g. as an enum with an underlying value field).
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/ECIESCryptor.kt, line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWQHdN13yZgV52pWwK:-MeWQHdOBKBhNQPB51R5:b775r7u) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/ECIESCryptor.kt#L21)):*
> ```
> that uses Google Tink as its crypto engine
> ```
This part isn't relevant, but rather the fact that this is a Cryptor for cipher suites that use ECIES.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSSqT6Q0WPsMAoOP7:-MeWSSqT6Q0WPsMAoOP8:b2r9jvj) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt#L28)):*
> ```
> KeyNotFoundException
> ```
Do we need the distinction between key not found and returning null (given that Kotlin nullables are basically an "optional type")?

If we do need the distinction, there should also be a separate method to check if a key exists so callers have a way to avoid the exception.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSMj3Duve1I4mgEhO:-MeWSMj3Duve1I4mgEhP:baquziz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt#L31)):*
> ```
> storePrivateKeyDER
> ```
https://developer.android.com/kotlin/style-guide#camel_case


<!-- Sent from Reviewable.io -->

2021-07-13 21:27 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 15 of 34 files reviewed, 14 unresolved discussions (waiting on @corbantek, @kungfucraig, @oliver-amzn, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWLT7tD7_ogrIh2Fsg:-MeW_BsfCJVmEQestg9K:brr6oaq) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is how we want to configure the dependencies.

The cryptor would always depend on the HybridCipherSuite, and I don't think we need an abstraction around signing at all.
</blockquote></details>

I kind of agree. Should I just delete this file for now?
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWQskX3ZsdfVxQj6b8:-MeWUe3bA5zqYfEjLSht:b-ot31po) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ByteArray
> ```
Use com.google.protobuf.ByteString where possible as an immutable byte collection type.
</blockquote></details>

A lot of crypto functions naturally return in ByteArray. It also means additional transformation back and forth in those types. I'd prefer to keep as is.


<!-- Sent from Reviewable.io -->

2021-07-13 22:28 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 7 of 38 files reviewed, 13 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Me70nKE4nl_j3FCn7HH:-MeWz6a-8v8rF_jgWHBk:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/f39a0eb303988ef5befd044318a672c175e38d96/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This is out-of-date. I changed this to `FakeHybridCryptor` that just reverses the string.
</blockquote></details>

👍


<!-- Sent from Reviewable.io -->

2021-07-13 23:35 UTC, SanjayVas requested changes
> Reviewed 2 of 32 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 9 of 38 files reviewed, 12 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWLT7tD7_ogrIh2Fsg:-MeXCKhN8JWs8zPmayFD:b-pkgs1b) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I kind of agree. Should I just delete this file for now?
</blockquote></details>

Sounds good to me
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWQskX3ZsdfVxQj6b8:-MeXCPwL46EGiIr3_KQ9:b-xnzmll) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt#L23)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

A lot of crypto functions naturally return in ByteArray. It also means additional transformation back and forth in those types. I'd prefer to keep as is.
</blockquote></details>

We prefer to keep things immutable whenever possible. Note that anything that's going to be read from or written to a protobuf message will need to be converted to/from a ByteString anyway, so there's little extra conversion cost.


<!-- Sent from Reviewable.io -->

2021-07-14 15:58 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 6 of 38 files reviewed, 10 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/client/BUILD.bazel, line 5 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWMmwNBysu9xGzhzXn:-Me_bNPr5lQVkhSa14cr:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/client/BUILD.bazel#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> test_target(":__subpackages__"),
> ```
Probably want this to be `"//visibility:public"` since I assume this is the piece that would be used by other repos.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/BUILD.bazel, line 9 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWPN2H6-a_QkPNB-i9:-Me_bX811HX4La75ZmZE:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> hybrid_encryption
> ```
nit: top-level glob everything target names should match the Bazel package name
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWQskX3ZsdfVxQj6b8:-Me_cZ2k1zcd-scxz3CA:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We prefer to keep things immutable whenever possible. Note that anything that's going to be read from or written to a protobuf message will need to be converted to/from a ByteString anyway, so there's little extra conversion cost.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/BUILD.bazel, line 7 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWS-UV0F0kPG5jqRRi:-Me_c_PLDve8bEbaVn50:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     testonly = True,
> ```
nit: you put `default_testonly = True` in the `package` declaration instead. This way if you split up the targets, they'll still be testonly.
</blockquote></details>

done
___
*[imports/java/org/mockito/BUILD.bazel, line 4 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWL-w_3hjhSqESjQP_:-Me_cgp2C4eTiT6hm1na:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/imports/java/org/mockito/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You should be able to get this from `@wfa_common_jvm//imports` instead of needing to define it here.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt, line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWLT7tD7_ogrIh2Fsg:-Me_jE5T8bGNFjApTlhO:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/client/ClientProviders.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sounds good to me
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt, line 8 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MdU6zZC1M5wi8Pyb2bt:-Me_b_eyCQ9XmFssuXiR:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/4161f08fe8b68777be0ca67a1ecb15ca719ba172/src/main/kotlin/org/wfanet/consentsignaling/crypto/TinkCrypto.kt#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's fine, assuming the intent is to use this for all `HybridCipherSuite` values that use ECIES. Though note that it should be `EciesCryptor` as per https://developer.android.com/kotlin/style-guide#camel_case
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hash/HashUtils.kt, line 20 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWN9pjAVKtsRSFIrBR:-Me_bVYa1IYGPS8-HPds:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hash/HashUtils.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> object CommonConstants {
> ```
We don't tend to wrap constants in objects to emulate a namespace. We just rely on the package path.

If you do want to group constants, do so by type (e.g. as an enum with an underlying value field).
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/ECIESCryptor.kt, line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWQHdN13yZgV52pWwK:-Me_bZHY7v3KzFEA4aXQ:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/ECIESCryptor.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> that uses Google Tink as its crypto engine
> ```
This part isn't relevant, but rather the fact that this is a Cryptor for cipher suites that use ECIES.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSSqT6Q0WPsMAoOP7:-Me_cbm8-spIsbG6bC7F:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> KeyNotFoundException
> ```
Do we need the distinction between key not found and returning null (given that Kotlin nullables are basically an "optional type")?

If we do need the distinction, there should also be a separate method to check if a key exists so callers have a way to avoid the exception.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSMj3Duve1I4mgEhO:-Me_cb1a9PZwicSTt4Pb:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8 [...]

2021-07-14 17:40 UTC, SanjayVas requested changes
> Reviewed 4 of 32 files at r3, 14 of 20 files at r6, 5 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 29 of 38 files reviewed, 5 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/FakeHybridCryptor.kt, line 22 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea3DqL-B0tsEXktFdl:-Mea3DqL-B0tsEXktFdm:bx2yt2w) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/FakeHybridCryptor.kt#L22)):*
> ```Kotlin
> 
> /**
>  * FakeHybridCryptor is an implementation of HybridCryptor that actually does no crypto. It only
> ```

nit: Use KDoc references for known symbols. See https://kotlinlang.org/docs/kotlin-doc.html#links-to-elements
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt, line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea5g7X1wcj82MSwzGc:-Mea5g7Y-He0QQZ7tF42:b-whcpjs) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt#L28)):*
> ```
> KEYSTORE_ADDRESS
> ```
nit: isn't this a key ID, not an address? (Address can imply something like hostname and port)
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSSqT6Q0WPsMAoOP7:-Mea3r_uEZ7pmnrFvoo1:b-ejc97l) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

done
</blockquote></details>

Can you explain why we'd need the distinction? I don't see any of the common reasons evident here (e.g. needing to propagate information about multiple different exceptional conditions, or `null` being a valid value).
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/PrivateKeyHandle.kt, line 42 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea4fO9A5fK0Nt31aCU:-Mea4fOADuYj0ZnEHcuO:b-u73kqp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/PrivateKeyHandle.kt#L42)):*
> ```
> // TODO
> ```
nit: I think if you put a comment between, the KDoc doesn't get associated with the function. In a case where you have a KDoc block, just stick the TODO inside of it.


<!-- Sent from Reviewable.io -->

2021-07-14 19:30 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 29 of 38 files reviewed, 3 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/FakeHybridCryptor.kt, line 22 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea3DqL-B0tsEXktFdl:-MeaT0sn3QOD95OrbFJP:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/FakeHybridCryptor.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Use KDoc references for known symbols. See https://kotlinlang.org/docs/kotlin-doc.html#links-to-elements
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt, line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea5g7X1wcj82MSwzGc:-MeaTfAf8QcQoAMVTqtZ:blp8cg5) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> KEYSTORE_ADDRESS
> ```
nit: isn't this a key ID, not an address? (Address can imply something like hostname and port)
</blockquote></details>

i changed this to ID for now. But, yes, I was actually thinking address.... https://github.com/google/tink/blob/master/docs/KEY-MANAGEMENT.md
`aws-kms://arn:aws:kms:<region>:<account-id>:key/<key-id>` vs `gcp-kms://projects/*/locations/*/keyRings/*/cryptoKeys/*`
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSSqT6Q0WPsMAoOP7:-MeaU5277hSEzXImz4YM:buu86cf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you explain why we'd need the distinction? I don't see any of the common reasons evident here (e.g. needing to propagate information about multiple different exceptional conditions, or `null` being a valid value).
</blockquote></details>

I believe Kyle was following Eli's pattern from here: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L28
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/PrivateKeyHandle.kt, line 42 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea4fO9A5fK0Nt31aCU:-MeaUG_P3V9CdfTtJn2b:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/PrivateKeyHandle.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> // TODO
> ```
nit: I think if you put a comment between, the KDoc doesn't get associated with the function. In a case where you have a KDoc block, just stick the TODO inside of it.
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-15 17:34 UTC, SanjayVas requested changes
> Reviewed 3 of 13 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 25 of 38 files reviewed, 3 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt, line 24 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MefCVrFDJvHJb_CmqDP:-MefCMwVELVOkHxVB6ig:bdw3q0t) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/643ab48be6d275fce514f3cbdafc1e78c68b4a50/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt#L24)):*
> ```Kotlin
> interface HybridCryptor {
>   /**
>    * [encrypt] will encrypt data using the public key stored in the [EncryptionPublicKey] Protobuf
> ```

Should be written as "Encrypts [data] using..."

See https://developer.android.com/kotlin/style-guide#summary_fragment
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt, line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea5g7X1wcj82MSwzGc:-MefCjBbDJI0jezBUx2u:bmc0u2o) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i changed this to ID for now. But, yes, I was actually thinking address.... https://github.com/google/tink/blob/master/docs/KEY-MANAGEMENT.md
`aws-kms://arn:aws:kms:<region>:<account-id>:key/<key-id>` vs `gcp-kms://projects/*/locations/*/keyRings/*/cryptoKeys/*`
</blockquote></details>

I think the fact that key IDs might be addresses can be an implementation detail.
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSSqT6Q0WPsMAoOP7:-MefDHEi2U1TmK9G97e1:b-d4ip8t) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I believe Kyle was following Eli's pattern from here: https://github.com/world-federation-of-advertisers/panel-exchange-client/blob/main/src/main/kotlin/org/wfanet/panelmatch/client/storage/Storage.kt#L28
</blockquote></details>

I would make the same suggestion to change that `Storage` interface. Compare to [StorageClient](https://github.com/world-federation-of-advertisers/common-jvm/blob/70f2a281097d28388b452dbe5b4ac0e86ca957e3/src/main/kotlin/org/wfanet/measurement/storage/StorageClient.kt)


<!-- Sent from Reviewable.io -->

2021-07-15 18:19 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4)* status: 25 of 38 files reviewed, 3 unresolved discussions (waiting on @corbantek, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt, line 24 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MefCVrFDJvHJb_CmqDP:-MefN_bxEQ5S1ZERt1QX:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/643ab48be6d275fce514f3cbdafc1e78c68b4a50/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/HybridCryptor.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should be written as "Encrypts [data] using..."

See https://developer.android.com/kotlin/style-guide#summary_fragment
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt, line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-Mea5g7X1wcj82MSwzGc:-MefNbZA3DRUJm2vFVEg:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/3f60f487aa22d43d84fbe81adaf7139b54b904e8/src/main/kotlin/org/wfanet/consentsignaling/crypto/hybridencryption/testing/AbstractHybridCryptorTest.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think the fact that key IDs might be addresses can be an implementation detail.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/4#-MeWSSqT6Q0WPsMAoOP7:-MefNdil2U_Tz9kHWd6N:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/2f42ed9803b8862bb6dbf07163eb57bf722f629d/src/main/kotlin/org/wfanet/consentsignaling/crypto/keys/KeyStore.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I would make the same suggestion to change that `Storage` interface. Compare to [StorageClient](https://github.com/world-federation-of-advertisers/common-jvm/blob/70f2a281097d28388b452dbe5b4ac0e86ca957e3/src/main/kotlin/org/wfanet/measurement/storage/StorageClient.kt)
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-16 21:05 UTC, closed without merging