Hybrid Cryptor; Data Provider and Duchy Consent
world-federation-of-advertisers/consent-signaling-client pull request #7
Opened 2021-07-20 14:04 UTC by stevenwarejones

Provides the following additions:
1. Fake Hybrid Cryptor
2. KeyStore/Private Key Handle
3. Data Provider Consent Signaling for Requisition
4. Duchy recognizes consent signal for requisition from data provider

2021-07-20 14:14 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 0 of 60 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 45 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3F9FW-pzFqVY8007n:-Mf3F9FW-pzFqVY8007o:bf04o8a) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L45)):*
> ```Kotlin
>     RequisitionSpec.parseFrom(hybridCryptor.decrypt(privateKeyHandle, encryptedRequisitionSpec))
>   val hashedEncryptedRequisitionSpec: ByteString =
>     hash(encryptedRequisitionSpec, dataProviderListSalt)
> ```

@sanjayvas - I don't think the data provider has access to the salt...where do they get the pre-computed hashedEncryptedRequisitionSpec from if they dont? I don't see it in the Requisition/ReqSpec protos
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 58 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3FNNDE6mKfWwc-Xp3:-Mf3FNNDE6mKfWwc-Xp4:bcrb8oa) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L58)):*
> ```Kotlin
>   print("3:${requisition.measurementSpec.data.joinToString()}\n")
>   print("4:${requisitionFingerprint.joinToString()}\n")
>   val privateKey: PrivateKey = requireNotNull(privateKeyHandle.toJavaPrivateKey("EC"))
> ```

@sanjayvas - which certificate should I read the algorithm from according to the spec?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3FXsh1ZVeW1T1_Nmu:-Mf3FXsh1ZVeW1T1_Nmv:b-laqtra) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L60)):*
> ```Kotlin
>   val privateKey: PrivateKey = requireNotNull(privateKeyHandle.toJavaPrivateKey("EC"))
>   val participationSignature =
>     privateKey.sign(certificate = readCertificate(dataProviderX509), data = requisitionFingerprint)
> ```

@sanjayvas is `dataProviderX509` the right certificate to read from here?


<!-- Sent from Reviewable.io -->

2021-07-20 16:47 UTC, kungfucraig reviewed
> Reviewed 1 of 34 files at r4, 11 of 40 files at r5, 16 of 27 files at r6, 3 of 6 files at r7, 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 35 of 60 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 34 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3V9YP2h-m85yxvakq:-Mf3V9YP2h-m85yxvakr:bif453s) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/28ffcd67d2454b9d29e246c891fe4ee24d4ae89c/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L34)):*
> ```Kotlin
>  * 2. Signs the RequisitionFingerprint resulting in the participationSignature
>  */
> fun indicateRequisitionParticipation(
> ```

This is kind of a weird name. Why not just "createParticipationSignature"? 
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/EciesCryptor.kt, line 22 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3WNNq7t-I4_SIpj9w:-Mf3WNNr7TmRz1Z23C4U:b38dz6j) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/28ffcd67d2454b9d29e246c891fe4ee24d4ae89c/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/EciesCryptor.kt#L22)):*
> ```Kotlin
> 
> /** TODO [EciesCryptor] will be an implementation of [HybridCryptor] that uses ICIES */
> class EciesCryptor : HybridCryptor {
> ```

Can you include an expansion of Ecies in the documentation? 
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/FakeHybridCryptor.kt, line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3Wob6Al0ATwJNTAao:-Mf3Wob6Al0ATwJNTAap:b-qtidjn) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/28ffcd67d2454b9d29e246c891fe4ee24d4ae89c/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/FakeHybridCryptor.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

I'm not entirely sure what the convention is for these types of classes, but typically I'd want to put them in a "testing" subdirectory. Ideally we have an annotation on the build rule that says they are only for testing as well.

@sanjayvas can you advise?


<!-- Sent from Reviewable.io -->

2021-07-20 19:46 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 35 of 60 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 34 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3V9YP2h-m85yxvakq:-Mf4RMog3bzqDkUSX6G7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/28ffcd67d2454b9d29e246c891fe4ee24d4ae89c/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L34)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This is kind of a weird name. Why not just "createParticipationSignature"? 
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/EciesCryptor.kt, line 22 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3WNNq7t-I4_SIpj9w:-Mf4RKOhCHFtMC_ck72p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/28ffcd67d2454b9d29e246c891fe4ee24d4ae89c/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/EciesCryptor.kt#L22)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you include an expansion of Ecies in the documentation? 
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/FakeHybridCryptor.kt, line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3Wob6Al0ATwJNTAao:-Mf4RB6m7JdLEcgfQaoZ:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/28ffcd67d2454b9d29e246c891fe4ee24d4ae89c/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/FakeHybridCryptor.kt#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'm not entirely sure what the convention is for these types of classes, but typically I'd want to put them in a "testing" subdirectory. Ideally we have an annotation on the build rule that says they are only for testing as well.

@sanjayvas can you advise?
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-21 20:01 UTC, SanjayVas requested changes
> Reviewed 1 of 34 files at r4, 5 of 40 files at r5, 9 of 27 files at r6, 2 of 6 files at r7, 1 of 4 files at r8, 5 of 9 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 31 of 60 files reviewed, 24 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[WORKSPACE, line 25 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9KAi48WbqiklG0nlU:-Mf9KAi5AtmRtXba8rQg:b4gq9hm) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/WORKSPACE#L25)):*
> ```
> # Measurement system.
> ```
nit: (I think my own fault from previous PR) This comment is incorrect, as it's not the CMMS repo being pulled in.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 45 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3F9FW-pzFqVY8007n:-Mf9KSUQEIHsLBsrAWY1:b-j1qwcb) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@sanjayvas - I don't think the data provider has access to the salt...where do they get the pre-computed hashedEncryptedRequisitionSpec from if they dont? I don't see it in the Requisition/ReqSpec protos
</blockquote></details>

The participant list (data provider list) is the only hash that's salted. All other hashes are unsalted.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 58 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3FNNDE6mKfWwc-Xp3:-Mf9LFsM0EbeKxDsSmu3:b2u41i0) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@sanjayvas - which certificate should I read the algorithm from according to the spec?
</blockquote></details>

You get the signing algorithm directly from the certificate, and the key type/algorithm from the public key of the certificate. You should probably pass the cert as the argument to `toJavaPrivateKey` rather than the key algorithm string.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3FXsh1ZVeW1T1_Nmu:-Mf9Lcny6_ieq_jBj-k0:bdxmgqm) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@sanjayvas is `dataProviderX509` the right certificate to read from here?
</blockquote></details>

Yes. EDP can only sign using the private key of their own certificate, after all.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 57 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9Ls8HEJhUt_F7mVew:-Mf9Ls8HEJhUt_F7mVex:bnish7r) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L57)):*
> ```
> also
> ```
nit: we generally use `apply` when we can for builders, and only use `also` when we have variable name conflicts.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 51 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9Ouq0CxilI083pJwr:-Mf9Ouq0CxilI083pJws:buf1qlb) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L51)):*
> ```Kotlin
>  */
> fun X509Certificate.verifySignature(signedData: SignedData): Boolean {
>   val verifier = Signature.getInstance(this.sigAlgName, jceProvider)
> ```

1. Just call the other overload from this one rather than duplicating the implementation.
2. I assume the `crypto` package more generic and not depend on the API messages. I imagine this should actually go into the `client` package.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/X509Testing.kt, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9dVwz8DyJfyZnN1c8:-Mf9dVwz8DyJfyZnN1c9:b-jwgxec) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/testing/X509Testing.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

I was actually thinking of adding a file like this in common-jvm as `Certs.kt` for the `certs` testdata filegroup.

Would you mind putting it there, since that's the repo that the test data is coming from?
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 53 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9MW5b6QeQV_k8dPPq:-Mf9MW5b6QeQV_k8dPPr:b-yroenr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L53)):*
> ```
>   // TODO: Verify DataProviderPublicKey is properly signed
> ```
EDP encryption public key doesn't get used here. We do however need to verify the certificate chain using the pre-exchanged EDP root cert.

Theoretically we only need to do this once for each cert we see, as the EDP cert could be reused across multiple measurements/requisitions, but that's an optimization that can be added even later.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 56 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9NSElBTgBBGkNajZj:-Mf9NSElBTgBBGkNajZk:b-m14zrr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L56)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   /**
>    * TODO Verify the dataProviderSignature has not been previously reused to protect against replay
>    * attacks
>    */
> ```
</details>

nit: regular comment rather than KDoc, since this is just a local var.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt, line 23 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9OECcD5VD5_ZQCGkS:-Mf9OECcD5VD5_ZQCGkT:b-guz5r6) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt#L23)):*
> ```
> hash
> ```
 nit: Since the API specifically calls for SHA256, I think it'd be fine to include that in the function name. Up to you.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt, line 29 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-M [...]

2021-07-22 17:44 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 31 of 60 files reviewed, 18 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[WORKSPACE, line 25 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9KAi48WbqiklG0nlU:-Mf9unqh7F7Fwfd0JFw_:bkkd8co) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/WORKSPACE#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> # Measurement system.
> ```
nit: (I think my own fault from previous PR) This comment is incorrect, as it's not the CMMS repo being pulled in.
</blockquote></details>

I fixed this in the follow-up PR already. https://github.com/world-federation-of-advertisers/consent-signaling-client/pull/9/files#diff-5493ff8e9397811510e780de47c57abb70137f1afe85d1519130dc3679d60ce5L25 but since I'm closing that one out, I folded it in here.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 45 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3F9FW-pzFqVY8007n:-Mf9uts-EIbEpbyiVS64:bskvqii) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The participant list (data provider list) is the only hash that's salted. All other hashes are unsalted.
</blockquote></details>

Yeah - sorry - posted this comment before I saw your Slack message. This is currently unsalted.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 58 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3FNNDE6mKfWwc-Xp3:-Mf9ynk-1Alh9b1CE0jZ:bntamxx) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You get the signing algorithm directly from the certificate, and the key type/algorithm from the public key of the certificate. You should probably pass the cert as the argument to `toJavaPrivateKey` rather than the key algorithm string.
</blockquote></details>

done. Thx for the clarification.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf3FXsh1ZVeW1T1_Nmu:-Mf9wGXl2YNlReR8dE_7:b-fmum4g) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/8d4ac572f47b55cee18f2b66309644a67578c1c9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. EDP can only sign using the private key of their own certificate, after all.
</blockquote></details>

Sounds good. Just wanted to double-check.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 57 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9Ls8HEJhUt_F7mVew:-Mf9vd523kupsEQ4L9Nx:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> also
> ```
nit: we generally use `apply` when we can for builders, and only use `also` when we have variable name conflicts.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 51 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9Ouq0CxilI083pJwr:-MfA5hDo1__Spz7zCmKZ:b-vviz8r) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. Just call the other overload from this one rather than duplicating the implementation.
2. I assume the `crypto` package more generic and not depend on the API messages. I imagine this should actually go into the `client` package.
</blockquote></details>

done. I didn't move the files around. Maybe we can do that in a follow-up.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/X509Testing.kt, line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9dVwz8DyJfyZnN1c8:-MfD53wL8sUaJ-1uevzc:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/testing/X509Testing.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I was actually thinking of adding a file like this in common-jvm as `Certs.kt` for the `certs` testdata filegroup.

Would you mind putting it there, since that's the repo that the test data is coming from?
</blockquote></details>

done.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 53 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9MW5b6QeQV_k8dPPq:-Mf9w1YEBrVPUw4S96oK:bmboz25) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   // TODO: Verify DataProviderPublicKey is properly signed
> ```
EDP encryption public key doesn't get used here. We do however need to verify the certificate chain using the pre-exchanged EDP root cert.

Theoretically we only need to do this once for each cert we see, as the EDP cert could be reused across multiple measurements/requisitions, but that's an optimization that can be added even later.
</blockquote></details>

I was trying to say we verify the chain by making sure the chain is valid (signed properly). Updated the comment to be more succint and clear.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 56 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9NSElBTgBBGkNajZj:-Mf9vuh79hgTVUrbPCuK:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>   /**
>    * TODO Verify the dataProviderSignature has not been previously reused to protect against replay
>    * attacks
>    */
> ```
nit: regular comment rather than KDoc, since this is just a local var.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Hashing.kt, line 23 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9OECcD5VD5_ZQCGkS:-M [...]

2021-07-22 19:09 UTC, SanjayVas requested changes
> Reviewed 22 of 29 files at r10, 2 of 8 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 26 of 62 files reviewed, 17 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEa60a2m4ZyoyTkHMR:-MfEa60a2m4ZyoyTkHMS:bs309q1) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L48)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>       /**
>        * We assume the signed measurementSpec was verified when the requisition was initially
>        * received by the data provider.
>        */
> ```
</details>

nit: regular comment rather than KDoc, but this should probably be stated in the function KDoc so callers know that the function does not verify any signatures in input.
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 54 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfENBeJ7e0B9ZTZpVkI:-MfENBeK4rzQ97EkDu46:bt7ehfk) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L54)):*
> ```
> readCertificate(dataProviderX509)
> ```
Just read this once into a local variable so you can reuse it in the following line.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 51 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfENgjtATsDgi7c1J-o:-MfENgjuB9ekx13KiXwX:b-wfupks) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L51)):*
> ```
> this.
> ```
nit: shouldn't need the `this.` qualification
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 81 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEXCUo2A-UX0i9QUKp:-MfEXCUo2A-UX0i9QUKq:bt7t22f) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L81)):*
> ```
> Base64.getEncoder().encodeToString(dataProviderParticipation.data.toByteArray())
> ```
Optionally could just compare to a raw UTF-8 string literal in fewer steps.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 33 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEahPo6fa6Usrxqoc2:-MfEahPo6fa6Usrxqoc3:b-mnucu) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L33)):*
> ```Kotlin
> class DuchyClientTest {
> 
>   val hybridCryptor: HybridCryptor = ReversingHybridCryptor()
> ```

These properties could likely be private. These also look to be constants and use CONSTANT_CASE (note that not all constants that use CONSTANT_CASE need be compile-time constants that use the `const` keyword). The private constants that don't depend on any state only accessible to DuchyClientTest can be declared outside of that class.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 53 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEbNh14HPRpdfk4Zq5:-MfEbNh249m5qe0Gu3Hb:blrfoh3) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L53)):*
> ```
> // This is pre-calculated using a fixed certificate from common-jvm
> ```
This is a property rather than a local variable, and therefore should use KDoc.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keys/InMemoryKeyStore.kt, line 29 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9Yu7z29JcU7bgrB6d:-MfETM0T0dCj6yaTUnXb:bmdewu3) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/crypto/keys/InMemoryKeyStore.kt#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i hadn't really thought about it. If you have an opinion, I can add it in.
</blockquote></details>

Probably want to match the behavior of the most restrictive keystore we tend to integrate with. A quick look at Google Cloud KMS docs and AWS KMS docs seems to imply that once a key is created with a given ID, it can only be disabled or destroyed. That said, there is a separate concept of key versioning for rotation, but even if we did manual key rotation I think we'd want an explicit method rather than just calling store on the same key.

Therefore, I'd suggest this method only support adding new private keys to the keystore.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keys/testing/AbstractKeyStoreTest.kt, line 31 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9d3AHAaJrJ6qN9-ly:-MfERkv45Gnxv5nRojlG:b-4m885s) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/crypto/keys/testing/AbstractKeyStoreTest.kt#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah. changed them to suspend. Are there any other parts of this I should make suspend?
</blockquote></details>

Not off the top of my head. In general, anything that could be async, which means anything that could make an RPC or do I/O.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/KeyStore.kt, line 39 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEP--I9zFjdB3KwVO6:-MfEP--I9zFjdB3KwVO7:b-es7y9p) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/KeyStore.kt#L39)):*
> ```Kotlin
>    * Accesses a [PrivateKeyHandle] via an existing key in [KeyStore].
>    *
>    * @return `null` if not present.
> ```

`@return` tag lines should exhaustively list the return information.

Basically, either the whole KDoc should be something that starts with "Returns" like
```
Returns a [PrivateKeyHandle] for the key specified by [id] or `null` if not found.
```

or have a summary line like "Accesses an existing private key specified by [id]." with the additional line
```
@return a [PrivateKeyHandle] for the key, or `null` if not found
```
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/KeyStore.kt, line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEOLhyAUZyMRIUJ8rz:-MfEOLhyAUZyMRIUJ8s-:b-8yz4ap) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/K [...]

2021-07-22 19:13 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 26 of 62 files reviewed, 17 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 33 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEahPo6fa6Usrxqoc2:-MfEcjvvCNuKor3Et6F5:bp91hhg) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These properties could likely be private. These also look to be constants and use CONSTANT_CASE (note that not all constants that use CONSTANT_CASE need be compile-time constants that use the `const` keyword). The private constants that don't depend on any state only accessible to DuchyClientTest can be declared outside of that class.
</blockquote></details>

More info from style guide on what counts as a constant, where they should be defined, and how to name them: https://developer.android.com/kotlin/style-guide#constant_names


<!-- Sent from Reviewable.io -->

2021-07-22 20:22 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 18 of 62 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEa60a2m4ZyoyTkHMR:-MfEftcM7QHB44jYbhzv:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>       /**
>        * We assume the signed measurementSpec was verified when the requisition was initially
>        * received by the data provider.
>        */
> ```
nit: regular comment rather than KDoc, but this should probably be stated in the function KDoc so callers know that the function does not verify any signatures in input.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt, line 54 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfENBeJ7e0B9ZTZpVkI:-MfEgDWX5VJ3thEi8-xR:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClient.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> readCertificate(dataProviderX509)
> ```
Just read this once into a local variable so you can reuse it in the following line.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt, line 51 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfENgjtATsDgi7c1J-o:-MfEgJvJ6ma0U_VMqeEs:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/crypto/Signatures.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> this.
> ```
nit: shouldn't need the `this.` qualification
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 81 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEXCUo2A-UX0i9QUKp:-MfElCl83jfgN34sLD7j:bgbebbp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L81)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Base64.getEncoder().encodeToString(dataProviderParticipation.data.toByteArray())
> ```
Optionally could just compare to a raw UTF-8 string literal in fewer steps.
</blockquote></details>

i kind of prefer base64 comparisons vs dealing with char sets. okay if I leave it as is?
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 33 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEahPo6fa6Usrxqoc2:-MfEofZU2rqIoqw69kPJ:b6bdp1h) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

More info from style guide on what counts as a constant, where they should be defined, and how to name them: https://developer.android.com/kotlin/style-guide#constant_names
</blockquote></details>

i made most of them private constants.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 53 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEbNh14HPRpdfk4Zq5:-MfElmR384lqZaklp5EO:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> // This is pre-calculated using a fixed certificate from common-jvm
> ```
This is a property rather than a local variable, and therefore should use KDoc.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keys/InMemoryKeyStore.kt, line 29 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-Mf9Yu7z29JcU7bgrB6d:-MfEkq4t51Z5_YOtf4ro:bj36of3) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/eb02871fab12970a92083064fd39a8d4c0bfe9f3/src/main/kotlin/org/wfanet/measurement/consent/crypto/keys/InMemoryKeyStore.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Probably want to match the behavior of the most restrictive keystore we tend to integrate with. A quick look at Google Cloud KMS docs and AWS KMS docs seems to imply that once a key is created with a given ID, it can only be disabled or destroyed. That said, there is a separate concept of key versioning for rotation, but even if we did manual key rotation I think we'd want an explicit method rather than just calling store on the same key.

Therefore, I'd suggest this method only support adding new private keys to the keystore.
</blockquote></details>

done. Throws an exception now. Added a test.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/KeyStore.kt, line 39 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEP--I9zFjdB3KwVO6:-MfEh0c81aW6cmMHDWSt:br0y67) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/KeyStore.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`@return` tag lines should exhaustively list the return information.

Basically, either the whole KDoc should be something that starts with "Returns" like
```
Returns a [PrivateKeyHandle] for the key specified by [id] or `null` if not found.
```

or have a summary line like "Accesses an existing private key specified by [id]." with the additional line
```
@return a [PrivateKeyHandle] for the key, or `null` if not found
```
</blockquote></details>

Done. I went with the latter.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/KeyStore.kt, line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEOLhyAUZyMRIUJ8rz:-MfEhRxc-d8tQtZ3ZGuP:buqpv6p) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/KeyStore.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Can only be access by this 'crypto' module.
> ```
How is this enforced? If it's not, perhaps this should say "Should" rather than "Can".
</blockquote></details>

changed to `should`
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/PrivateKeyHandle.kt, li [...]

2021-07-23 19:01 UTC, SanjayVas approved these changes
> Reviewed 10 of 42 files at r2, 11 of 40 files at r5, 4 of 27 files at r6, 5 of 29 files at r10, 3 of 8 files at r11, 9 of 9 files at r12, 3 of 3 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: all files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[WORKSPACE, line 30 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJj1Rt97WO1UGKiK1b:-MfJj1Ru-KgsaFa-tZLl:b-kgqi00) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/WORKSPACE#L30)):*
> ```
> 1854779043b0b12a0f43e78940778877fb73a3db
> ```
Don't merge this PR until you swap this with a commit that has been merged into the main branch.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 13 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJhI-Y8nxWiOT0XFjO:-MfJhI-Y8nxWiOT0XFjP:b-13zqmf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L13)):*
> ```Starlark
> 
> generate_root_certificate(
>     name = "edp_1_root",
> ```

nit: I'd recommend giving each of these a different subject common name to really show they're intended to be used by different entities.
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 19 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJhej3BbST6cfPDDwi:-MfJhej3BbST6cfPDDwj:b6zfhl7) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L19)):*
> ```Kotlin
> import java.io.File
> 
> private const val TESTDATA_DIR = "src/main/kotlin/org/wfanet/measurement/consent/testing/"
> ```

nit: use Paths for this. While we're generally assuming we'll be in environments where `/` is the path separator, might as well avoid encoding that assumption when possible.
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt, line 81 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfEXCUo2A-UX0i9QUKp:-MfJi5aD0VlVMbq3j52E:bdoad7c) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/b5bf6fbdfb939d364cc173b781e1ce81861042a9/src/test/kotlin/org/wfanet/measurement/consent/client/dataprovider/DataProviderClientTest.kt#L81)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i kind of prefer base64 comparisons vs dealing with char sets. okay if I leave it as is?
</blockquote></details>

Yep. Hence "optionally" in my comment :)
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 35 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJiQGnAHoHTev1wt7b:-MfJiQGnAHoHTev1wt7c:bxrca2v) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L35)):*
> ```Kotlin
> private val SOME_DATA_PROVIDER_LIST_SALT = ByteString.copyFromUtf8("some-salt-0")
> private val SOME_SERIALIZED_DATA_PROVIDER_LIST = ByteString.copyFromUtf8("some-data-provider-list")
> // We use a fixed certificate so we can verify the signature against a known certificate
> ```

nit: KDoc
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/PrivateKeyHandle.kt, line 47 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJgsUW4qfRcxtUB2gV:-MfJgsUXCmTh0Og6ALna:byprv11) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/PrivateKeyHandle.kt#L47)):*
> ```
> @return 
> ```
nit: The summary fragment is required by style guide for KDoc, but the `@return` tag is not. That is to say if the only relevant thing is what it returns, just make that the summary line.


<!-- Sent from Reviewable.io -->

2021-07-23 20:50 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: all files reviewed, 12 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 27 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK5RHTAMUA8dPXk_SQ:-MfK5RHU3EUNKF2HOAqt:bv5v4ck) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L27)):*
> ```Kotlin
>   val dataProviderListSalt: ByteString,
>   val measurementSpec: ByteString,
>   val encryptedRequisitionSpec: ByteString,
> ```

is encryptedRequisitionSpec redundant?
we only need the hash of it, which is the requisitionSpecHash inside Requisition
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 30 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK6VtA4NxccpbeT3T9:-MfK6VtA4NxccpbeT3TA:b-5yumfn) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L30)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> data class Requisition(
>   val dataProviderCertificate: ByteString,
>   val requisitionSpecHash: ByteString
> )
> ```
</details>

please add comments to all fields, so it is easier to know, for example, if the requisitionSpec here is encrypted or not.
```
data class Computation(
  // Serialized `DataProviderList` from public API.
  val dataProviderList: ByteString,
 // Salt for SHA256 hash of `data_provider_list`.
  val dataProviderListSalt: ByteString,
  // Serialized `MeasurementSpec` from public API.
  val measurementSpec: ByteString
)

data class Requisition(
  // X.509 certificate in DER format which can be verified using the
  // `DataProvider`'s root certificate.
   val dataProviderCertificate: ByteString,
// SHA256 hash of encrypted `RequisitionSpec` from public API.
   val requisitionSpecHash: ByteString
 )
```


<!-- Sent from Reviewable.io -->

2021-07-23 20:58 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: all files reviewed, 13 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel, line 9 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK7yBB0doLXvJ3sfgT:-MfK7yBB0doLXvJ3sfgU:bsy2ksa) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel#L9)):*
> ```
> hybridencryption
> ```
nit: `hybrid_encryption`, we use snake_case for kt_jvm_library names I think


<!-- Sent from Reviewable.io -->

2021-07-23 21:59 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: all files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[WORKSPACE, line 30 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJj1Rt97WO1UGKiK1b:-MfKFLvI8KMrJpGeS2H9:b-gbw0dd) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/WORKSPACE#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> 1854779043b0b12a0f43e78940778877fb73a3db
> ```
Don't merge this PR until you swap this with a commit that has been merged into the main branch.
</blockquote></details>

of course
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel, line 13 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJhI-Y8nxWiOT0XFjO:-MfKK9OX0uivzHQLSyqI:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/testing/BUILD.bazel#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I'd recommend giving each of these a different subject common name to really show they're intended to be used by different entities.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 19 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJhej3BbST6cfPDDwi:-MfKMkyq8tu4gOloqlPy:b-rnrapz) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use Paths for this. While we're generally assuming we'll be in environments where `/` is the path separator, might as well avoid encoding that assumption when possible.
</blockquote></details>

done. 
___
*[src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt, line 35 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJiQGnAHoHTev1wt7b:-MfKN-gz6WsuuklNYKfc:bww43fl) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/test/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClientTest.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: KDoc
</blockquote></details>

changed to kdoc
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 27 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK5RHTAMUA8dPXk_SQ:-MfKFYB1C0Jt9DJzol2L:bzqmdr) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L27)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

is encryptedRequisitionSpec redundant?
we only need the hash of it, which is the requisitionSpecHash inside Requisition
</blockquote></details>

good catch. 
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 30 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK6VtA4NxccpbeT3T9:-MfKHhgk4lR0MCqz1o2Y:bq8mirw) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L30)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> data class Requisition(
>   val dataProviderCertificate: ByteString,
>   val requisitionSpecHash: ByteString
> )
> ```
please add comments to all fields, so it is easier to know, for example, if the requisitionSpec here is encrypted or not.
```
data class Computation(
  // Serialized `DataProviderList` from public API.
  val dataProviderList: ByteString,
 // Salt for SHA256 hash of `data_provider_list`.
  val dataProviderListSalt: ByteString,
  // Serialized `MeasurementSpec` from public API.
  val measurementSpec: ByteString
)

data class Requisition(
  // X.509 certificate in DER format which can be verified using the
  // `DataProvider`'s root certificate.
   val dataProviderCertificate: ByteString,
// SHA256 hash of encrypted `RequisitionSpec` from public API.
   val requisitionSpecHash: ByteString
 )
```
</blockquote></details>

done. for clarification, I believe all these fields come from the computationDetails and requisitionDetails protos of the internal api for the duchy
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel, line 9 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK7yBB0doLXvJ3sfgT:-MfKHvVd5TTHISyh9rnq:be5md74) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel#L9)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> hybridencryption
> ```
nit: `hybrid_encryption`, we use snake_case for kt_jvm_library names I think
</blockquote></details>

I had it that way but Sanjay wanted it to match the directory name. I could change the directory name to have an underscore but that doesn't seem to be the convention either.
___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/PrivateKeyHandle.kt, line 47 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfJgsUW4qfRcxtUB2gV:-MfKIIlB56dHz92tERvt:bz5o5qv) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/crypto/keystore/PrivateKeyHandle.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> @return 
> ```
nit: The summary fragment is required by style guide for KDoc, but the `@return` tag is not. That is to say if the only relevant thing is what it returns, just make that the summary line.
</blockquote></details>

done. thanks for the tip.


<!-- Sent from Reviewable.io -->

2021-07-23 22:00 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 56 of 62 files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel, line 9 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK7yBB0doLXvJ3sfgT:-MfKNHTVEGU3VoPENN5z:bj9v42f) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel#L9)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I had it that way but Sanjay wanted it to match the directory name. I could change the directory name to have an underscore but that doesn't seem to be the convention either.
</blockquote></details>

This is because we don't use snake_case in package names, and this target name should match the package name so the shorthand can be used in the Bazel label.


<!-- Sent from Reviewable.io -->

2021-07-23 22:03 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 56 of 62 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel, line 9 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfK7yBB0doLXvJ3sfgT:-MfKOEEk9mlix0ZuAQh9:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/257a250e034f9914a2027f8ebd0b0583d39f4689/src/main/kotlin/org/wfanet/measurement/consent/crypto/hybridencryption/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is because we don't use snake_case in package names, and this target name should match the package name so the shorthand can be used in the Bazel label.
</blockquote></details>

sg


<!-- Sent from Reviewable.io -->

2021-07-27 23:28 UTC, stevenwarejones reviewed
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 56 of 62 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-27 23:30 UTC, stevenwarejones reviewed
> Dismissed @kungfucraig from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 56 of 62 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-27 23:37 UTC, stevenwarejones reviewed
@sanjayvas - I know you approved it but I think you need to re-approve it. It won't let me merge because it says its waiting on your review.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-:-MfeK4IF0ra0HhlOybbB:b-925g5a)* status: 56 of 62 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-07-28 00:24 UTC, SanjayVas approved these changes
> Reviewed 3 of 6 files at r14, 1 of 1 files at r15, 2 of 2 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 32 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfeUcbnAKEGW-8a_s4E:-MfeUcbnAKEGW-8a_s4F:bmbrpwy) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7206a67f87f1aad78e7de9a6e9f9cd2190a0945e/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L32)):*
> ```
> File("$TESTDATA_DIR_PATH/edp_1.pem")
> ```
TESTDATA_DIR_PATH.resolve("edp_1.pem").toFile()
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 23 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfeUTI2Arvyn1l7ACEO:-MfeUTI3CcCpGxw6S7mw:b-7via8d) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7206a67f87f1aad78e7de9a6e9f9cd2190a0945e/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L23)):*
> ```Kotlin
> import org.wfanet.measurement.consent.crypto.verifySignature
> 
> // Fields from the computationDetails proto of the internal duchy api
> ```

nit: all these should be KDoc


<!-- Sent from Reviewable.io -->

2021-07-28 01:36 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt, line 32 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfeUcbnAKEGW-8a_s4E:-MfejfyIBTTbYv_9e2wt:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7206a67f87f1aad78e7de9a6e9f9cd2190a0945e/src/main/kotlin/org/wfanet/measurement/consent/testing/CertificateTesting.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> File("$TESTDATA_DIR_PATH/edp_1.pem")
> ```
TESTDATA_DIR_PATH.resolve("edp_1.pem").toFile()
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt, line 23 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7#-MfeUTI2Arvyn1l7ACEO:-MfekA17EaQlsWEdxlOu:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/consent-signaling-client/blob/7206a67f87f1aad78e7de9a6e9f9cd2190a0945e/src/main/kotlin/org/wfanet/measurement/consent/client/duchy/DuchyClient.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: all these should be KDoc
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-07-28 13:36 UTC, stevenwarejones reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: 60 of 62 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-07-28 17:17 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r17.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-07-28 17:40 UTC, merged